### ISSUE TITLE
Error at end of process.

### ISSUE THREAD

**Issue by APOS80** [OpenDroneMap/WebODM#1095]
### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Chrome Win 10

### What is the problem

Error at end of processing

### What should be the expected behavior?

At least getting the results already produced and maybe a better error message.

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? Please include multiple screenshots of the problem! If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Settings:
No crop
Ultra detail
ORB

Error messages.:
... output truncated at undefined lines ...

Postprocessing face infos 78%...

Postprocessing face infos 79%...

Postprocessing face infos 79%...

Postprocessing face infos 79%...

Postprocessing face infos 79%...

Postprocessing face infos 79%...

Postprocessing face infos 79%...

Postprocessing face infos 79%...

Postprocessing face infos 79%...

Postprocessing face infos 79%...

Postprocessing face infos 80%...

Postprocessing face infos 80%...

Postprocessing face infos 81%...

Postprocessing face infos 83%...

Postprocessing face infos 86%...

Postprocessing face infos 88%...

Postprocessing face infos 89%...

Postprocessing face infos 91%...

Postprocessing face infos 93%...

Postprocessing face infos 93%...

Postprocessing face infos 94%...

Postprocessing face infos 95%...

Postprocessing face infos 95%...

Postprocessing face infos 95%...

Postprocessing face infos 97%...

Postprocessing face infos 100%... done. (Took 0.005s)
Maximum quality of a face within an image: 0.990907
Clamping qualities to 0.982879 within normalization.
Optimizing:
Time[s]	Energy
0	3363
0	3197
0	3120
0	3062
0	3046
0	3033
0	3025
0	3016
0	3010
0	3010
0	3008
0	3006
0	3005
0	3002
0	3001
0	3000
1338 faces have not been seen
Took: 4.274s
Generating texture patches:
Running... done. (Took 4.886s)
64 texture patches.
Running global seam leveling:
Create matrices for optimization...  done.
Lhs dimensionality: 3056 x 3056
Calculating adjustments:
Color channel 0: CG took 86 iterations. Residual is 9.73671e-05
Color channel 1: CG took 86 iterations. Residual is 9.67909e-05
Color channel 2: CG took 101 iterations. Residual is 8.98589e-05
Took 0.003 seconds

Adjusting texture patches 0%...
Adjusting texture patches 0%...

Adjusting texture patches 0%...

Adjusting texture patches 0%...

Adjusting texture patches 0%...

Adjusting texture patches 0%...

Adjusting texture patches 0%...

Adjusting texture patches 0%...

Adjusting texture patches 0%...

Adjusting texture patches 0%...

Adjusting texture patches 0%...

Adjusting texture patches 0%...

Adjusting texture patches 2%...

Adjusting texture patches 3%...

Adjusting texture patches 5%...

Adjusting texture patches 6%...

Adjusting texture patches 8%...

Adjusting texture patches 9%...

Adjusting texture patches 11%...

Adjusting texture patches 12%...

Adjusting texture patches 14%...

Adjusting texture patches 15%...

Adjusting texture patches 17%...

Adjusting texture patches 18%...

Adjusting texture patches 20%...

Adjusting texture patches 22%...

Adjusting texture patches 23%...

Adjusting texture patches 25%...

Adjusting texture patches 26%...

Adjusting texture patches 28%...

Adjusting texture patches 29%...

Adjusting texture patches 31%...

Adjusting texture patches 32%...

Adjusting texture patches 34%...

Adjusting texture patches 35%...

Adjusting texture patches 37%...

Adjusting texture patches 38%...

Adjusting texture patches 40%...

Adjusting texture patches 42%...

Adjusting texture patches 43%...

Adjusting texture patches 45%...

Adjusting texture patches 46%...

Adjusting texture patches 48%...

Adjusting texture patches 49%...

Adjusting texture patches 51%...

Adjusting texture patches 52%...

Adjusting texture patches 54%...

Adjusting texture patches 55%...

Adjusting texture patches 57%...

Adjusting texture patches 58%...

Adjusting texture patches 60%...

Adjusting texture patches 62%...

Adjusting texture patches 63%...

Adjusting texture patches 65%...

Adjusting texture patches 66%...

Adjusting texture patches 68%...

Adjusting texture patches 69%...

Adjusting texture patches 71%...

Adjusting texture patches 72%...

Adjusting texture patches 74%...

Adjusting texture patches 75%...

Adjusting texture patches 77%...

Adjusting texture patches 78%...

Adjusting texture patches 80%...

Adjusting texture patches 82%...

Adjusting texture patches 100%... done. (Took 1.758s)
Running local seam leveling:

Blending texture patches 0%...

Blending texture patches 0%...

Blending texture patches 0%...

Blending texture patches 0%...

Blending texture patches 0%...
Blending texture patches 0%...

Blending texture patches 0%...

Blending texture patches 0%...

Blending texture patches 0%...

Blending texture patches 0%...

Blending texture patches 0%...

Blending texture patches 0%...

Blending texture patches 2%...

Blending texture patches 3%...

Blending texture patches 5%...

Blending texture patches 8%...

Blending texture patches 9%...

Blending texture patches 11%...

Blending texture patches 11%...

Blending texture patches 12%...

Blending texture patches 14%...

Blending texture patches 15%...

Blending texture patches 17%...

Blending texture patches 20%...

Blending texture patches 20%...

Blending texture patches 22%...

Blending texture patches 23%...

Blending texture patches 25%...

Blending texture patches 26%...

Blending texture patches 28%...

Blending texture patches 29%...

Blending texture patches 31%...

Blending texture patches 32%...

Blending texture patches 34%...

Blending texture patches 35%...

Blending texture patches 37%...

Blending texture patches 38%...

Blending texture patches 40%...

Blending texture patches 42%...

Blending texture patches 43%...

Blending texture patches 45%...

Blending texture patches 46%...

Blending texture patches 48%...

Blending texture patches 51%...

Blending texture patches 51%...

Blending texture patches 52%...

Blending texture patches 54%...

Blending texture patches 55%...

Blending texture patches 57%...

Blending texture patches 58%...

Blending texture patches 60%...

Blending texture patches 62%...

Blending texture patches 63%...

Blending texture patches 65%...

Blending texture patches 69%...

Blending texture patches 69%...

Blending texture patches 69%...

Blending texture patches 71%...

Blending texture patches 72%...

Blending texture patches 74%...

Blending texture patches 75%...

Blending texture patches 77%...

Blending texture patches 78%...

Blending texture patches 80%...

Blending texture patches 82%...

Blending texture patches 100%... done. (Took 7.581s)
Generating texture atlases:
Sorting texture patches... done.

Working on atlas 1 100%... done.
Finalizing texture atlases... done. (Took: 0s)
Building objmodel:
Saving model... done.
Whole texturing procedure took: 128.936s
[INFO]    Finished mvs_texturing stage
[INFO]    Running odm_georeferencing stage
[WARNING] GCPs could not be loaded for writing to G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\ground_control_points.gpkg
[INFO]    Georeferencing point cloud
[INFO]    running pdal translate -i "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_filterpoints\point_cloud.ply" -o "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.laz" ferry transformation --filters.ferry.dimensions="views => UserData" --writers.las.compression="lazip" --filters.transformation.matrix="1 0 0 334438.0 0 1 0 6556553.0 0 0 1 0 0 0 0 1" --writers.las.offset_x=334438.0 --writers.las.offset_y=6556553.0 --writers.las.offset_z=0 --writers.las.a_srs="+proj=utm +zone=34 +datum=WGS84 +units=m +no_defs +type=crs"
[INFO]    Calculating cropping area and generating bounds shapefile from point cloud
[INFO]    running pdal translate -i "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.laz" -o "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.decimated.las" decimation --filters.decimation.step=40
[INFO]    running pdal info --boundary --filters.hexbin.edge_size=1 --filters.hexbin.threshold=0 "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.decimated.las" > "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.boundary.json"
[WARNING] Very small crop area detected, we will not smooth it.
[INFO]    running pdal info --summary "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.laz" > "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.summary.json"
[INFO]    running ogr2ogr -overwrite -f GPKG -a_srs "+proj=utm +zone=34 +datum=WGS84 +units=m +no_defs" "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.bounds.gpkg" "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.bounds.geojson"
[INFO]    Creating Entwine Point Tile output
[INFO]    running untwine --temp_dir "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\entwine_pointcloud-tmp" --files "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.laz" --output_dir "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\entwine_pointcloud"
[INFO]    Finished odm_georeferencing stage
[INFO]    Running odm_dem stage
[INFO]    Classify: False
[INFO]    Create DSM: True
[INFO]    Create DTM: False
[INFO]    DEM input file G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.laz found: True
[INFO]    running pdal info --summary "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.laz" > "C:\Users\APO\AppData\Local\Temp\tmpgkllevrs.json"
[INFO]    Point cloud bounds are [minx: 334393.3913, maxx: 334396.6755] [miny: 6556521.446, maxy: 6556525.717]
[INFO]    DEM resolution is (214, 165), max tile size is 4096, will split DEM generation into 1 tiles
[INFO]    Generating G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm_r0.04_x0_y0.tif (max, radius: 0.04, resolution: 0.02)
[INFO]    Generating G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm_r0.02_x0_y0.tif (max, radius: 0.02, resolution: 0.02)
[INFO]    Generating G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm_r0.01_x0_y0.tif (max, radius: 0.01, resolution: 0.02)
[INFO]    Pipeline file: C:\Users\APO\AppData\Local\Temp\tmp2lkb64n3.json
[INFO]    Pipeline file: C:\Users\APO\AppData\Local\Temp\tmpjn_1nmv0.json
[INFO]    running pdal pipeline -i "C:\Users\APO\AppData\Local\Temp\tmp2lkb64n3.json"
[INFO]    Pipeline file: C:\Users\APO\AppData\Local\Temp\tmpu2buh03z.json
[INFO]    running pdal pipeline -i "C:\Users\APO\AppData\Local\Temp\tmpjn_1nmv0.json"
[INFO]    running pdal pipeline -i "C:\Users\APO\AppData\Local\Temp\tmpu2buh03z.json"
[INFO]    running gdalbuildvrt -input_file_list "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\tiles_list.txt" "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\tiles.vrt"
0...10...20...30...40...50...60...70...80...90...100 - done.
[INFO]    running gdal_translate -co NUM_THREADS=12 -co BIGTIFF=IF_SAFER --config GDAL_CACHEMAX 45.8% "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\tiles.vrt" "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\tiles.tmp.tif"
Input file size is 165, 214
0...10...20...30...40...50...60...70...80...90...100 - done.
[INFO]    running gdal_translate -co NUM_THREADS=12 -co BIGTIFF=IF_SAFER --config GDAL_CACHEMAX 45.8% -outsize 10% 0 "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\tiles.tmp.tif" "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\tiles.small.tif"
...100 - done.
0
...10
...20...30...40..
.50
.
.
.
60.
.
.
70.
.
.80.
..90
..
.
Input file size is 165, 214
0...10...20...30...40...50...60...70...80...90...100 - done.
[INFO]    running gdalbuildvrt -resolution highest -r bilinear "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\merged.vrt" "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\tiles.small_filled.tif" "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\tiles.tmp.tif"
0...10...20...30...40...50...60...70...80...90...100 - done.
[INFO]    running gdal_translate -co NUM_THREADS=12 -co TILED=YES -co BIGTIFF=IF_SAFER -co COMPRESS=DEFLATE --config GDAL_CACHEMAX 45.8% "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\merged.vrt" "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\tiles.tif"
Input file size is 165, 214
0...10...20...30...40...50...60...70...80...90...100 - done.
[INFO]    Starting smoothing...
[INFO]    Smoothing iteration 1
[INFO]    Completed smoothing to create G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm.tif in 0:00:00.155036
[INFO]    Completed dsm.tif in 0:01:50.762788
[INFO]    Cropping G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm.tif
[INFO]    running gdalwarp -cutline "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.bounds.gpkg" -crop_to_cutline -co TILED=YES -co COMPRESS=DEFLATE -co BLOCKXSIZE=512 -co BLOCKYSIZE=512 -co BIGTIFF=IF_SAFER -co NUM_THREADS=12  "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm.original.tif" "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm.tif" --config GDAL_CACHEMAX 45.75%
Creating output file that is 324P x 389L.
Processing G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm.original.tif [1/1] : 0Using internal nodata values (e.g. -9999) for image G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm.original.tif.
Copying nodata values from source G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm.original.tif to destination G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm.tif.
...10...20...30...40...50...60...70...80...90...100 - done.
[INFO]    Optimizing G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm.tif as Cloud Optimized GeoTIFF
[INFO]    running gdal_translate -of COG -co NUM_THREADS=12 -co BLOCKSIZE=256 -co COMPRESS=DEFLATE -co PREDICTOR=2 -co BIGTIFF=IF_SAFER -co RESAMPLING=NEAREST --config GDAL_CACHEMAX 45.75% --config GDAL_NUM_THREADS 12 "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm.tif" "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_dem\dsm_cogeo.tif"
Input file size is 324, 389
0...10...20...30...40...50...60...70...80...90...100 - done.
[INFO]    Finished odm_dem stage
[INFO]    Running odm_orthophoto stage
[INFO]    running "G:\WebODM\resources\app\apps\ODM\SuperBuild\install\bin\odm_orthophoto" -inputFiles "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_texturing_25d\odm_textured_model_geo.obj" -logFile "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto_log.txt" -outputFile "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto_render.tif" -resolution 50.0 -verbose -outputCornerFile "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto_corners.txt"
Writing corners to: G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto_corners.txt

Reading mesh file... G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_texturing_25d\odm_textured_model_geo.obj
Mesh file read.

Set boundary to contain entire model.
Boundary points:
Point 1: -44.6087 -31.4866
Point 2: -44.6087 -27.253
Point 3: -41.3831 -27.253
Point 4: -41.3831 -31.4866

Model bounds x : -44.6087 -> -41.3831
Model bounds y : -31.4866 -> -27.253
Model area : 13.6559m2
Model resolution, width x height : 162x212
Translating and scaling mesh...
.. mesh translated and scaled.

Rendering the ortho photo...
Texture channels: 3
Texture depth: 8bit
Material 0 rendered.
... model rendered

Writing ortho photo to G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto_render.tif
Writing corner coordinates to G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto_corners.txt
Orthophoto generation done.
[INFO]    Creating GeoTIFF
[INFO]    running gdal_translate -a_ullr 334393.3913154602 6556525.746953964 334396.6169166565 6556521.513353348 -co TILED=YES -co COMPRESS=DEFLATE -co PREDICTOR=2 -co BIGTIFF=IF_SAFER -co BLOCKXSIZE=512 -co BLOCKYSIZE=512 -co NUM_THREADS=12 -a_srs "+proj=utm +zone=34 +datum=WGS84 +units=m +no_defs +type=crs" --config GDAL_CACHEMAX 45.8% --config GDAL_TIFF_INTERNAL_MASK YES "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto_render.tif" "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto.tif" > "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\gdal_translate_log.txt"
[INFO]    Cropping G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto.tif
[INFO]    running gdalwarp -cutline "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_georeferencing\odm_georeferenced_model.bounds.gpkg" -crop_to_cutline -co TILED=YES -co COMPRESS=DEFLATE -co PREDICTOR=2 -co BIGTIFF=IF_SAFER -co BLOCKXSIZE=512 -co BLOCKYSIZE=512 -co NUM_THREADS=12 -dstalpha "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto.original.tif" "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto.tif" --config GDAL_CACHEMAX 45.8%
Using band 4 of source image as alpha.
Creating output file that is 325P x 391L.
Processing G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto.original.tif [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.
[INFO]    Optimizing G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto.tif as Cloud Optimized GeoTIFF
[INFO]    running gdal_translate -of COG -co NUM_THREADS=12 -co BLOCKSIZE=256 -co COMPRESS=DEFLATE -co PREDICTOR=2 -co BIGTIFF=IF_SAFER -co RESAMPLING=NEAREST --config GDAL_CACHEMAX 45.8% --config GDAL_NUM_THREADS 12 "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto.tif" "G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_orthophoto\odm_orthophoto_cogeo.tif"
Input file size is 325, 391
0...10...20...30...40...50...60...70...80...90...100 - done.
[INFO]    Finished odm_orthophoto stage
[INFO]    Running odm_report stage
[INFO]    Exporting shots.geojson
[INFO]    Wrote G:\WebODM\resources\app\apps\NodeODM\data\3c126123-d303-43b6-8287-142cb830749a\odm_report\shots.geojson
[WARNING] Cannot generate report, OpenSfM stats are missing
100 - done.
Traceback (most recent call last):
File "G:\WebODM\resources\app\apps\ODM\\run.py", line 53, in <module>
retcode = app.execute()
File "G:\WebODM\resources\app\apps\ODM\stages\odm_app.py", line 130, in execute
raise e
File "G:\WebODM\resources\app\apps\ODM\stages\odm_app.py", line 94, in execute
self.first_stage.run()
File "G:\WebODM\resources\app\apps\ODM\opendm\types.py", line 347, in run
self.next_stage.run(outputs)
File "G:\WebODM\resources\app\apps\ODM\opendm\types.py", line 347, in run
self.next_stage.run(outputs)
File "G:\WebODM\resources\app\apps\ODM\opendm\types.py", line 347, in run
self.next_stage.run(outputs)
[Previous line repeated 8 more times]
File "G:\WebODM\resources\app\apps\ODM\opendm\types.py", line 328, in run
self.process(self.args, outputs)
File "G:\WebODM\resources\app\apps\ODM\stages\odm_report.py", line 124, in process
if odm_stats.get('point_cloud_statistics') and point_cloud_file and views_dimension:
AttributeError: 'NoneType' object has no attribute 'get

**Comment by APOS80** [comment]
I was able to find the results, they were very distorted.

I'll try without GCPs and se if that can be a problem.
