### ISSUE TITLE
WebODM 1.9.13 : localhost node always "offline"

### ISSUE THREAD

**Issue by Majstor** [OpenDroneMap/WebODM#1161]
### How did you install WebODM (docker, installer, etc.)?

Fedora 35, using podman containers

### What's your browser and operating system?
Fedora 35, Mozilla Firefox 98.0

### What is the problem?
WebODM constantly sees nodeodm as offline, and can't do any work. 

### How can we reproduce this?
If i check output, i can see the node is running :
```
$ ./webodm.sh start
Checking for podman...   OK
Checking for podman-compose...   OK
Starting WebODM...

Using the following environment:
================================
Host: localhost
Port: 8000
Media directory: appmedia
SSL: NO
SSL key: 
SSL certificate: 
SSL insecure port redirect: 80
Celery Broker: redis://broker
Default Nodes: 1
================================
Make sure to issue a ./webodm.sh down if you decide to change the environment.

podman-compose -f docker-compose.yml -f docker-compose.nodeodm.yml up --scale node-odm=1
['podman', '--version', '']
using podman version: 3.4.4
** merged:
{
 "_dirname": "/home/majstor/WebODM_latest",
 "version": "2.1",
 "volumes": {
   "dbdata": null,
   "appmedia": null
 },
 "services": {
   "db": {
     "image": "opendronemap/webodm_db",
     "container_name": "db",
     "ports": [
       "5432"
     ],
     "volumes": [
       "dbdata:/var/lib/postgresql/data:Z"
     ],
     "restart": "unless-stopped",
     "oom_score_adj": -100
   },
   "webapp": {
     "image": "opendronemap/webodm_webapp",
     "container_name": "webapp",
     "entrypoint": "/bin/bash",
     "command": "-c \"/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/start.sh\"",
     "volumes": [
       "appmedia:/webodm/app/media:z"
     ],
     "ports": [
       "8000:8000"
     ],
     "depends_on": [
       "db",
       "broker",
       "worker",
       "node-odm"
     ],
     "environment": {
       "WO_PORT": null,
       "WO_HOST": null,
       "WO_DEBUG": null,
       "WO_BROKER": null,
       "WO_DEV": null,
       "WO_DEFAULT_NODES": null
     },
     "restart": "unless-stopped",
     "oom_score_adj": 0
   },
   "broker": {
     "image": "redis",
     "container_name": "broker",
     "restart": "unless-stopped",
     "oom_score_adj": -500
   },
   "worker": {
     "image": "opendronemap/webodm_webapp",
     "container_name": "worker",
     "entrypoint": "/bin/bash",
     "command": "-c \"/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/wait-for-it.sh -t 0 webapp:8000 -- /webodm/worker.sh start\"",
     "volumes": [
       "appmedia:/webodm/app/media:z"
     ],
     "depends_on": [
       "db",
       "broker"
     ],
     "environment": {
       "WO_BROKER": null,
       "WO_DEBUG": null
     },
     "restart": "unless-stopped",
     "oom_score_adj": 250
   },
   "node-odm": {
     "image": "opendronemap/nodeodm",
     "ports": [
       "3000"
     ],
     "restart": "unless-stopped",
     "oom_score_adj": 500
   }
 }
}
** excluding:  set()
podman volume inspect webodm_latest_dbdata || podman volume create webodm_latest_dbdata
['podman', 'volume', 'inspect', 'webodm_latest_dbdata']
['podman', 'network', 'exists', 'webodm_latest_default']
podman create --name=db --label io.podman.compose.config-hash=123 --label io.podman.compose.project=webodm_latest --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=webodm_latest --label com.docker.compose.project.working_dir=/home/majstor/WebODM_latest --label com.docker.compose.project.config_files=docker-compose.yml,docker-compose.nodeodm.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=db -v webodm_latest_dbdata:/var/lib/postgresql/data:Z --net webodm_latest_default --network-alias db -p 5432 --restart unless-stopped opendronemap/webodm_db
Error: error creating container storage: the container name "db" is already in use by "0475e14ebcf80a30d62e87d14f74f2992a5ff4c9cde1b7c1ebb2b2b5d65646d8". You have to remove that container to be able to reuse that name.: that name is already in use
exit code: 125
['podman', 'network', 'exists', 'webodm_latest_default']
podman create --name=broker --label io.podman.compose.config-hash=123 --label io.podman.compose.project=webodm_latest --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=webodm_latest --label com.docker.compose.project.working_dir=/home/majstor/WebODM_latest --label com.docker.compose.project.config_files=docker-compose.yml,docker-compose.nodeodm.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=broker --net webodm_latest_default --network-alias broker --restart unless-stopped redis
Error: error creating container storage: the container name "broker" is already in use by "7729751d56c10034e6dec8e78dcd07d429522a1dc08823d100aad23cf598aa79". You have to remove that container to be able to reuse that name.: that name is already in use
exit code: 125
['podman', 'network', 'exists', 'webodm_latest_default']
podman create --name=webodm_latest_node-odm_1 --label io.podman.compose.config-hash=123 --label io.podman.compose.project=webodm_latest --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=webodm_latest --label com.docker.compose.project.working_dir=/home/majstor/WebODM_latest --label com.docker.compose.project.config_files=docker-compose.yml,docker-compose.nodeodm.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=node-odm --net webodm_latest_default --network-alias node-odm -p 3000 --restart unless-stopped opendronemap/nodeodm
Error: error creating container storage: the container name "webodm_latest_node-odm_1" is already in use by "aec03d2f5e5c01207978535e769e7a88d97535273a3c89d83859dfdadb9b6855". You have to remove that container to be able to reuse that name.: that name is already in use
exit code: 125
podman volume inspect webodm_latest_appmedia || podman volume create webodm_latest_appmedia
['podman', 'volume', 'inspect', 'webodm_latest_appmedia']
['podman', 'network', 'exists', 'webodm_latest_default']
podman create --name=worker --label io.podman.compose.config-hash=123 --label io.podman.compose.project=webodm_latest --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=webodm_latest --label com.docker.compose.project.working_dir=/home/majstor/WebODM_latest --label com.docker.compose.project.config_files=docker-compose.yml,docker-compose.nodeodm.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=worker -e WO_BROKER -e WO_DEBUG -v webodm_latest_appmedia:/webodm/app/media:z --net webodm_latest_default --network-alias worker --restart unless-stopped --entrypoint ["/bin/bash"] opendronemap/webodm_webapp -c /webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/wait-for-it.sh -t 0 webapp:8000 -- /webodm/worker.sh start
Error: error creating container storage: the container name "worker" is already in use by "c1a9370ae5136ec0259602e879b431de05fae9bc639a75a5727d12a7dcc22ac1". You have to remove that container to be able to reuse that name.: that name is already in use
exit code: 125
podman volume inspect webodm_latest_appmedia || podman volume create webodm_latest_appmedia
['podman', 'volume', 'inspect', 'webodm_latest_appmedia']
['podman', 'network', 'exists', 'webodm_latest_default']
podman create --name=webapp --label io.podman.compose.config-hash=123 --label io.podman.compose.project=webodm_latest --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=webodm_latest --label com.docker.compose.project.working_dir=/home/majstor/WebODM_latest --label com.docker.compose.project.config_files=docker-compose.yml,docker-compose.nodeodm.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=webapp -e WO_PORT -e WO_HOST -e WO_DEBUG -e WO_BROKER -e WO_DEV -e WO_DEFAULT_NODES -v webodm_latest_appmedia:/webodm/app/media:z --net webodm_latest_default --network-alias webapp -p 8000:8000 --restart unless-stopped --entrypoint ["/bin/bash"] opendronemap/webodm_webapp -c /webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/start.sh
Error: error creating container storage: the container name "webapp" is already in use by "690790a99661d7d140d94401fc2544389aa6324199ae0179f675956c4cccd818". You have to remove that container to be able to reuse that name.: that name is already in use
exit code: 125
podman start -a db

PostgreSQL Database directory appears to contain a database; Skipping initialization

LOG:  database system was shut down at 2022-03-26 19:10:29 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
podman start -a broker
1:C 26 Mar 2022 19:11:55.013 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 26 Mar 2022 19:11:55.013 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 26 Mar 2022 19:11:55.013 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 26 Mar 2022 19:11:55.013 * monotonic clock: POSIX clock_gettime
1:M 26 Mar 2022 19:11:55.014 * Running mode=standalone, port=6379.
1:M 26 Mar 2022 19:11:55.014 # Server initialized
1:M 26 Mar 2022 19:11:55.014 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 26 Mar 2022 19:11:55.014 * Loading RDB produced by version 6.2.6
1:M 26 Mar 2022 19:11:55.014 * RDB age 86 seconds
1:M 26 Mar 2022 19:11:55.014 * RDB memory usage when created 0.77 Mb
1:M 26 Mar 2022 19:11:55.014 # Done loading RDB, keys loaded: 0, keys expired: 0.
1:M 26 Mar 2022 19:11:55.014 * DB loaded from disk: 0.000 seconds
1:M 26 Mar 2022 19:11:55.014 * Ready to accept connections
podman start -a webodm_latest_node-odm_1
info: Authentication using NoTokenRequired
info: Listening on 0.0.0.0:6367 UDP for progress updates
info: Initialized 0 tasks
info: Checking for orphaned directories to be removed...
info: Server has started on port 3000
podman start -a worker
Postgres is up - executing command
wait-for-it.sh: waiting for broker:6379 without a timeout
wait-for-it.sh: broker:6379 is available after 0 seconds
wait-for-it.sh: waiting for webapp:8000 without a timeout
podman start -a webapp
Postgres is up - executing command
wait-for-it.sh: waiting for broker:6379 without a timeout
wait-for-it.sh: broker:6379 is available after 0 seconds

_       __     __    ____  ____  __  ___
| |     / /__  / /_  / __ \/ __ \/  |/  /
| | /| / / _ \/ __ \/ / / / / / / /|_/ / 
| |/ |/ /  __/ /_/ / /_/ / /_/ / /  / /  
|__/|__/\___/_.___/\____/_____/_/  /_/   


Checking python version... 3.x, good!
Checking GDAL version... GDAL 3.2.2, released 2021/03/05, excellent!
Running migrations
Operations to perform:
 Apply all migrations: admin, app, auth, contenttypes, guardian, nodeodm, sessions
Running migrations:
 No migrations to apply.
Traceback (most recent call last):
 File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 492, in connect
   sock = self._connect()
 File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 550, in _connect
   raise err
 File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 538, in _connect
   sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/webodm/manage.py", line 22, in <module>
   execute_from_command_line(sys.argv)
 File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
   utility.execute()
 File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 375, in execute
   self.fetch_command(subcommand).run_from_argv(self.argv)
 File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 323, in run_from_argv
   self.execute(*args, **cmd_options)
 File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 364, in execute
   output = self.handle(*args, **options)
 File "/usr/local/lib/python3.9/dist-packages/django/core/management/commands/shell.py", line 92, in handle
   exec(sys.stdin.read())
 File "<string>", line 9, in <module>
 File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 1225, in delete
   return self.execute_command('DEL', *names)
 File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 772, in execute_command
   connection = pool.get_connection(command_name, **options)
 File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 994, in get_connection
   connection.connect()
 File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 497, in connect
   raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
Checking for celery...   OK
WO_BROKER environment variable is not set. Defaulting to redis://localhost
Scheduler has shutdown.
Generating nginx configurations from templates...
- nginx/nginx-ssl.conf
- nginx/nginx.conf
celery beat v4.4.0 (cliffs) is starting.
[2022-03-26 19:12:00 +0000] [88] [INFO] Starting gunicorn 19.7.1
[2022-03-26 19:12:00 +0000] [88] [INFO] Listening at: unix:/tmp/gunicorn.sock (88)
[2022-03-26 19:12:00 +0000] [88] [INFO] Using worker: sync
/usr/lib/python3.9/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
 return io.open(fd, *args, **kwargs)
[2022-03-26 19:12:00 +0000] [139] [INFO] Booting worker with pid: 139
[2022-03-26 19:12:00 +0000] [140] [INFO] Booting worker with pid: 140
[2022-03-26 19:12:00 +0000] [141] [INFO] Booting worker with pid: 141
[2022-03-26 19:12:00 +0000] [142] [INFO] Booting worker with pid: 142
__    -    ... __   -        _
LocalTime -> 2022-03-26 19:12:00
Configuration ->
   . broker -> redis://localhost:6379//
   . loader -> celery.loaders.app.AppLoader
   . scheduler -> celery.beat.PersistentScheduler
   . db -> celerybeat-schedule
   . logfile -> [stderr]@%WARNING
   . maxinterval -> 5.00 minutes (300s)
[2022-03-26 19:12:00 +0000] [143] [INFO] Booting worker with pid: 143
[2022-03-26 19:12:00 +0000] [144] [INFO] Booting worker with pid: 144
[2022-03-26 19:12:00 +0000] [145] [INFO] Booting worker with pid: 145
[2022-03-26 19:12:00 +0000] [146] [INFO] Booting worker with pid: 146
[2022-03-26 19:12:00 +0000] [147] [INFO] Booting worker with pid: 147
[2022-03-26 19:12:00 +0000] [148] [INFO] Booting worker with pid: 148
[2022-03-26 19:12:00 +0000] [149] [INFO] Booting worker with pid: 149
[2022-03-26 19:12:01 +0000] [150] [INFO] Booting worker with pid: 150
[2022-03-26 19:12:01 +0000] [151] [INFO] Booting worker with pid: 151
[2022-03-26 19:12:01 +0000] [152] [INFO] Booting worker with pid: 152
[2022-03-26 19:12:01 +0000] [153] [INFO] Booting worker with pid: 153
[2022-03-26 19:12:01 +0000] [154] [INFO] Booting worker with pid: 154
[2022-03-26 19:12:01 +0000] [155] [INFO] Booting worker with pid: 155
[2022-03-26 19:12:01 +0000] [156] [INFO] Booting worker with pid: 156
[2022-03-26 19:12:01 +0000] [157] [INFO] Booting worker with pid: 157
[2022-03-26 19:12:01 +0000] [158] [INFO] Booting worker with pid: 158
[2022-03-26 19:12:01 +0000] [159] [INFO] Booting worker with pid: 159
[2022-03-26 19:12:01 +0000] [160] [INFO] Booting worker with pid: 160
[2022-03-26 19:12:01 +0000] [161] [INFO] Booting worker with pid: 161
[2022-03-26 19:12:01 +0000] [162] [INFO] Booting worker with pid: 162
[2022-03-26 19:12:01 +0000] [163] [INFO] Booting worker with pid: 163
[2022-03-26 19:12:01 +0000] [164] [INFO] Booting worker with pid: 164
[2022-03-26 19:12:01 +0000] [165] [INFO] Booting worker with pid: 165
[2022-03-26 19:12:01 +0000] [166] [INFO] Booting worker with pid: 166
[2022-03-26 19:12:01 +0000] [167] [INFO] Booting worker with pid: 167
[2022-03-26 19:12:01 +0000] [168] [INFO] Booting worker with pid: 168
[2022-03-26 19:12:01 +0000] [169] [INFO] Booting worker with pid: 169
wait-for-it.sh: webapp:8000 is available after 4 seconds
Checking for celery...   OK
WO_BROKER environment variable is not set. Defaulting to redis://localhost
Starting worker using broker at redis://localhost
[2022-03-26 19:12:02 +0000] [170] [INFO] Booting worker with pid: 170
[2022-03-26 19:12:02 +0000] [171] [INFO] Booting worker with pid: 171
/usr/local/lib/python3.9/dist-packages/celery/platforms.py:800: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

 warnings.warn(RuntimeWarning(ROOT_DISCOURAGED.format(
[2022-03-26 19:12:02,892: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds...


Trying to establish communication...
INFO Booting WebODM 1.9.13
WARNING Debug mode is ON (for development this is OK)
[2022-03-26 19:12:04,894: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds...

INFO Registered [coreplugins.changedetection.plugin]
INFO Registered [coreplugins.contours.plugin]
INFO Registered [coreplugins.diagnostic.plugin]
[2022-03-26 19:12:05,575: ERROR/MainProcess] beat: Connection error: Error 111 connecting to localhost:6379. Connection refused.. Trying again in 2.0 seconds...
INFO Registered [coreplugins.elevationmap.plugin]
INFO Registered [coreplugins.fullscreen.plugin]
INFO Registered [coreplugins.measure.plugin]
INFO Registered [coreplugins.openaerialmap.plugin]
INFO Registered [coreplugins.posm-gcpi.plugin]
ERROR Cannot connect to celery broker at redis://localhost. Make sure that your redis-server is running at that address: Error 111 connecting to localhost:6379. Connection refused.

Congratulations! └@(･◡･)@┐
==========================

If there are no errors, WebODM should be up and running!

Open a web browser and navigate to http://localhost:8000

NOTE: Windows users using docker should replace localhost with the IP of their docker machine's IP. To find what that is, run: docker-machine ip
[2022-03-26 19:12:07,578: ERROR/MainProcess] beat: Connection error: Error 111 connecting to localhost:6379. Connection refused.. Trying again in 4.0 seconds...
[2022-03-26 19:12:08,900: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds...

[2022-03-26 19:12:11,583: ERROR/MainProcess] beat: Connection error: Error 111 connecting to localhost:6379. Connection refused.. Trying again in 6.0 seconds...
[2022-03-26 19:12:14,908: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds...
```

**Comment by pierotofy** [comment]
Hi @Majstor,

It looks like there is some information missing from your issue that will be needed in order to diagnose and fix the problem at hand. Please take a look at the [Issue Template](https://github.com/OpenDroneMap/WebODM/blob/master/ISSUE_TEMPLATE.md), which will tell you **exactly** what your issue has to contain in order to be processable.

Also, double check that this is the right place. If you are just asking for information, reporting feedback or proposing a few feature, the right place to ask is the [Community Forum](http://community.opendronemap.org/c/webodm), not here.

I'm marking this one now as needing some more information. Please understand that if you do not provide that information within the next week (until 2022-03-27 15:40) I'll close this issue so it doesn't clutter the bug tracker.

Cheers!
~ Your friendly GitIssueBot

PS: I'm just an automated script, not a human being.

**Comment by Majstor** [comment]
See nodeodm container's log :
```
info: Checking for orphaned directories to be removed...
info: Server has started on port 3000
info: Closing server
info: Exiting...
info: Authentication using NoTokenRequired
info: Listening on 0.0.0.0:6367 UDP for progress updates
info: Initialized 0 tasks
info: Checking for orphaned directories to be removed...
info: Server has started on port 3000
info: Closing server
info: Exiting...
info: Authentication using NoTokenRequired
info: Listening on 0.0.0.0:6367 UDP for progress updates
info: Initialized 0 tasks
info: Checking for orphaned directories to be removed...
info: Server has started on port 3000
info: Closing server
info: Exiting...
info: Authentication using NoTokenRequired
info: Listening on 0.0.0.0:6367 UDP for progress updates
info: Initialized 0 tasks
info: Checking for orphaned directories to be removed...
info: Server has started on port 3000
```

**Comment by pierotofy** [comment]
Mm, we don't officially support podman, so you might need to make changes to WebODM/NodeODM to make it work (open a pull request?) :pray: 

Since this doesn't look like a bug, I'm going to close this for now.

**Comment by Majstor** [comment]
It has worked nice before this update. Any reasons ?

**Comment by pierotofy** [comment]
I'm not really sure! We haven't changed our docker stuff in a while.

**Comment by Majstor** [comment]
And ? No solution for me ?

**Comment by pierotofy** [comment]
I'm sorry you feel that way.

https://docs.opendronemap.org/requesting-features/#how-to-request-features

We don't officially support podman.

You can either help us improve the software by opening a pull request or you could contribute in some other way to add support for podman.

**Comment by Groupeffect** [comment]
Hi @Majstor,
I had the same problem with podman-compose and I just added the `env_file` attribute to the docker-compose.yml services `webapp` and `worker` like this:

```
# docker-compose.yml
...
webapp:
   ...
    env_file:
      - .env
   ...

worker:
   ...
    env_file:
      - .env
   ...
```
this way you set the `WO_BROKER` value to `redis://broker` from the `.env` file.
I hope this works for you, too.
Additionally you can add the prefix docker.io like: `image: docker.io/<image_name>`  to the docker-compose image paths.

**Comment by paultrino** [comment]
@Groupeffect  You are my hero!!!! I also was having issues with Podman. Those two small changes in my docker-compose did it! 💪

**Comment by paultrino** [comment]
@pierotofy Would it be ok to put @Groupeffect s suggestion into docker compose? I know podman is not supported, but it would just work out of the box for podman users with a minimal change. (PS, great book!)

**Comment by paultrino** [comment]
@pierotofy  Piero, also a solid thank you to you as well for all your hard work on ODM 🍻. Your classiness, dedication, leadership, and contributions to GIS / FOSS / GiScience are greatly appreciated. Especially for drone newbs like myself. (Amazing book btw! highly recommended!!!!! [OpenDroneMap: The Missing Guide - 2nd Edition](https://odmbook.com/2)
