### ISSUE TITLE
Idle WebODM system's redis and celery processes eventually consume 100% CPU

### ISSUE THREAD

**Issue by robby-dermody** [OpenDroneMap/WebODM#1244]
### How did you install WebODM (docker, installer, etc.)?

From the instructions at https://github.com/OpenDroneMap/WebODM#getting-started

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Issue does not involve the client or browser. Server OS is Ubuntu 22.04.1 LTS as a VM running under VMWare ESXi (given 6 vCPUs, 32gb of RAM, 100GB of HD space). Running the newest `master` from git.

`free -m` output:
```
local@dronemap:~/WebODM$ free -m
               total        used        free      shared  buff/cache   available
Mem:           32105        2255       24589          15        5259       29382
Swap:           8191           0        8191
```

`df -h` output:
```
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           3.2G  1.7M  3.2G   1% /run
/dev/sda2        98G   28G   66G  30% /
tmpfs            16G     0   16G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.2G  4.0K  3.2G   1% /run/user/1000
```

`uname -a` output: `Linux dronemap 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### What is the problem?

I have a WebODM system that is totally idle (haven't processed a single thing on it yet). After starting up the services via the standard `./webodm.sh start` command and letting them sit for awhile (unsure exactly how long... a few hours, a few days), eventually the redis and celery processes will both consume 50-100% CPU (`uptime` shows `load average: 1.30, 1.33, 1.30`).

I looked at the logs of all docker processes, the ones that stick out are an infinite loop of the following from the `webapp` container:
```
redis.exceptions.ConnectionError: Error 104 while writing to socket. Connection reset by peer.
Exception ignored in: <function AsyncResult.__del__ at 0x7f9a50200f70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/celery/result.py", line 389, in __del__
    self.backend.remove_pending_result(self)
  File "/usr/local/lib/python3.9/dist-packages/celery/backends/asynchronous.py", line 180, in remove_pending_result
    self.on_result_fulfilled(result)
  File "/usr/local/lib/python3.9/dist-packages/celery/backends/asynchronous.py", line 188, in on_result_fulfilled
    self.result_consumer.cancel_for(result.id)
  File "/usr/local/lib/python3.9/dist-packages/celery/backends/redis.py", line 148, in cancel_for
    self._pubsub.unsubscribe(key)
  File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 3112, in unsubscribe
    retval = self.execute_command('UNSUBSCRIBE', *args)
  File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 3009, in execute_command
    self._execute(connection, connection.send_command, *args)
  File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 3013, in _execute
    return command(*args)
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 620, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 612, in send_packed_command
    raise ConnectionError("Error %s while writing to socket. %s." %
```

And an infinite loop of the following from the following from the `broker` container:
```
1:M 28 Aug 2022 16:21:24.204 # Client id=19212 addr=172.18.0.6:45214 laddr=172.18.0.2:6379 fd=21 name= age=2 idle=0 flags=P db=0 sub=390449 psub=0 multi=-1 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=2048 rbp=1024 obl=0 oll=1647 omem=33770088 tot-mem=49455616 events=rw cmd=subscribe user=default redir=-1 resp=2 closed for overcoming of output buffer limits.
1:M 28 Aug 2022 16:21:29.285 # Client id=19213 addr=172.18.0.6:45216 laddr=172.18.0.2:6379 fd=21 name= age=2 idle=0 flags=P db=0 sub=390450 psub=0 multi=-1 qbuf=0 qbuf-free=20474 argv-mem=0 multi-mem=0 rbs=2048 rbp=1024 obl=0 oll=1647 omem=33770088 tot-mem=49455640 events=rw cmd=unsubscribe user=default redir=-1 resp=2 closed for overcoming of output buffer limits.
```

With a little googling, it appears that the redis output buffer may not be sized large enough. What is confusing is that this is a stock install, updated code, totally idle. I could modify the output buffer limits in a `redis.conf` file as described at https://redis.io/docs/reference/clients/#output-buffer-limits for a potential "fix", but it appears that WebODM uses a stock redis docker image with no custom config, or ability to easily modify or use a custom config without modifying code, and I'd rather not deal with forking and maintaining the code.

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

Unknown, I just installed WebODM on a well-provisioned Ubuntu VM and got this.

**Comment by pierotofy** [comment]
So I finally had time to revisit this; the core issue is that celery will store the results of async tasks (tombstones) in redis for 1 day. But since we run several tasks at ~5 second intervals, you end up with more than 24,000 keys just lying around. Trying to sync that exceeds the client buffer limits.

Instead of increasing the buffer limits, I opted for ignoring the task results whenever appropriate, as most period task don't return a value. 

If the issue persists, feel free to reopen!
