### ISSUE TITLE
Invalid PLY file (expected 'property uint8 red')  ====  Dumping Info for Geeks (developers need this to fix bugs)

### ISSUE THREAD

**Issue by xx1425942154** [OpenDroneMap/WebODM#1438]
Invalid PLY file (expected 'property uint8 red')

====

Dumping Info for Geeks (developers need this to fix bugs)

Child returned 1

Traceback (most recent call last):

File "/code/stages/odn_app.py", line 81, in execute self. first_stage. run()

File "/code/opendn/types.py", line 438, in run

self. next_stage. run (outputs)

File "/code/opendm/types.py", line 438, in run

self. next_stage, run (outputs)

File "/code/opendm/types.py", line 438, in run

self. next_stage. run (outputs)

[Previous line repeated 2 more times]

File "/code/opendm/types.py", line 417, in run

self.process(self. args, outputs)

File "/code/stages/odm_filterpoints.py", line 52, in process

point_cloud. filter(inputPointCloud, tree.filtered_point_cloud, tree. filtered_point_cloud_stats,

File "/code/opendm/point_cloud. py", line 106, in filter

system. run( "%s" %s' % (context. fpcfilter_path, " ".join(args)))

File "/code/opendn/systen py", line 112, in run

raise SubprocessException("Child returned 0".format(retcode), retcode)

opendm. system. SubprocessException: Child returned 1

Done, human-readable information to follow...

I failed to build with 1000 images, I am not sure if this is a bug, at least I reported this error when I built, which makes me unable to continue the construction, please help me solve this problem.thanks ！！！

**Comment by pierotofy** [comment]
1. Make sure you are using the latest version of WebODM/ODM
2. How can we reproduce this? Include images, parameters used, full task output.
