### ISSUE TITLE
Always getting error, if GCP are only on one side of the area to be constructed into orthophoto.

### ISSUE THREAD

**Issue by duiveldoder** [OpenDroneMap/WebODM#1448]
console.txt:

[INFO]    DTM is turned on, automatically turning on point cloud classification
[INFO]    Initializing ODM 3.3.4 - Tue Dec 19 07:28:59  2023
[INFO]    ==============
[INFO]    3d_tiles: False
[INFO]    align: None
[INFO]    auto_boundary: True
[INFO]    auto_boundary_distance: 0
[INFO]    bg_removal: False
[INFO]    boundary: {}
[INFO]    build_overviews: False
[INFO]    camera_lens: auto
[INFO]    cameras: {}
[INFO]    cog: True
[INFO]    copy_to: None
[INFO]    crop: 3
[INFO]    dem_decimation: 1
[INFO]    dem_euclidean_map: False
[INFO]    dem_gapfill_steps: 3
[INFO]    dem_resolution: 1.0
[INFO]    dsm: True
[INFO]    dtm: True
[INFO]    end_with: odm_postprocess
[INFO]    fast_orthophoto: False
[INFO]    feature_quality: ultra
[INFO]    feature_type: sift
[INFO]    force_gps: False
[INFO]    gcp: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/gcp/gcp_list.txt
[INFO]    geo: None
[INFO]    gltf: True
[INFO]    gps_accuracy: 10
[INFO]    ignore_gsd: False
[INFO]    matcher_neighbors: 0
[INFO]    matcher_order: 0
[INFO]    matcher_type: bruteforce
[INFO]    max_concurrency: 4
[INFO]    merge: all
[INFO]    mesh_octree_depth: 11
[INFO]    mesh_size: 200000
[INFO]    min_num_features: 10000
[INFO]    name: 4a922b8e-20c6-4e49-ba61-56db96adb02e
[INFO]    no_gpu: True
[INFO]    optimize_disk_space: False
[INFO]    orthophoto_compression: DEFLATE
[INFO]    orthophoto_cutline: True
[INFO]    orthophoto_kmz: False
[INFO]    orthophoto_no_tiled: False
[INFO]    orthophoto_png: False
[INFO]    orthophoto_resolution: 1.0
[INFO]    pc_classify: True
[INFO]    pc_copc: False
[INFO]    pc_csv: False
[INFO]    pc_ept: True
[INFO]    pc_filter: 2.5
[INFO]    pc_las: False
[INFO]    pc_quality: ultra
[INFO]    pc_rectify: False
[INFO]    pc_sample: 0
[INFO]    pc_skip_geometric: False
[INFO]    primary_band: auto
[INFO]    project_path: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e
[INFO]    radiometric_calibration: none
[INFO]    rerun: None
[INFO]    rerun_all: False
[INFO]    rerun_from: ['odm_postprocess']
[INFO]    rolling_shutter: False
[INFO]    rolling_shutter_readout: 0
[INFO]    sfm_algorithm: incremental
[INFO]    sfm_no_partial: False
[INFO]    skip_3dmodel: False
[INFO]    skip_band_alignment: False
[INFO]    skip_orthophoto: False
[INFO]    skip_report: False
[INFO]    sky_removal: False
[INFO]    sm_cluster: None
[INFO]    sm_no_align: False
[INFO]    smrf_scalar: 1.25
[INFO]    smrf_slope: 0.15
[INFO]    smrf_threshold: 0.5
[INFO]    smrf_window: 18.0
[INFO]    split: 999999
[INFO]    split_image_groups: None
[INFO]    split_overlap: 150
[INFO]    texturing_keep_unseen_faces: False
[INFO]    texturing_single_material: False
[INFO]    texturing_skip_global_seam_leveling: False
[INFO]    tiles: False
[INFO]    use_3dmesh: False
[INFO]    use_exif: False
[INFO]    use_fixed_camera_params: False
[INFO]    use_hybrid_bundle_adjustment: False
[INFO]    video_limit: 500
[INFO]    video_resolution: 4000
[INFO]    ==============
[INFO]    Running dataset stage
[INFO]    Loading dataset from: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/images
[INFO]    Loading images database: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/images.json
[INFO]    Found 350 usable images
[INFO]    Coordinates file already exist: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/odm_georeferencing/coords.txt
[INFO]    GCP file already exist: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/odm_georeferencing/gcp_list_utm.txt
[INFO]    Finished dataset stage
[INFO]    Running split stage
[INFO]    Normal dataset, will process all at once.
[INFO]    Finished split stage
[INFO]    Running merge stage
[INFO]    Normal dataset, nothing to merge.
[INFO]    Finished merge stage
[INFO]    Running opensfm stage
[WARNING] /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/opensfm/image_list.txt already exists, not rerunning OpenSfM setup
[WARNING] /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/opensfm/exif already exists, not rerunning photo to metadata
[WARNING] Detect features already done: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/opensfm/features exists
[WARNING] Match features already done: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/opensfm/matches exists
[WARNING] Found a valid OpenSfM tracks file in: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/opensfm/tracks.csv
[WARNING] Found a valid OpenSfM reconstruction file in: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/opensfm/reconstruction.json
[INFO]    Already extracted cameras
[INFO]    Export reconstruction stats
[WARNING] Found existing reconstruction stats /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/opensfm/stats/stats.json
[WARNING] Will skip exporting /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/opensfm/reconstruction.geocoords.json
[INFO]    Undistorting /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/opensfm ...
[WARNING] Already undistorted (nominal)
[WARNING] Found a valid OpenSfM NVM reconstruction file in: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/opensfm/undistorted/reconstruction.nvm
[INFO]    Finished opensfm stage
[INFO]    Running openmvs stage
[WARNING] Found a valid OpenMVS reconstruction file in: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/opensfm/undistorted/openmvs/scene_dense_dense_filtered.ply
[INFO]    Finished openmvs stage
[INFO]    Running odm_filterpoints stage
[WARNING] Found a valid point cloud file in: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/odm_filterpoints/point_cloud.ply
[INFO]    Finished odm_filterpoints stage
[INFO]    Running odm_meshing stage
[WARNING] Found a valid ODM Mesh file in: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/odm_meshing/odm_mesh.ply
[WARNING] Found a valid ODM 2.5D Mesh file in: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/odm_meshing/odm_25dmesh.ply
[INFO]    Finished odm_meshing stage
[INFO]    Running mvs_texturing stage
[INFO]    Writing MVS Textured file in: /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/odm_texturing/odm_textured_model_geo.obj
[INFO]    Removing old tmp directory /var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/odm_texturing/tmp
[INFO]    running "/code/SuperBuild/install/bin/texrecon" "/var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/opensfm/undistorted/reconstruction.nvm" "/var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/odm_meshing/odm_mesh.ply" "/var/www/data/4a922b8e-20c6-4e49-ba61-56db96adb02e/odm_texturing/odm_textured_model_geo" -d gmi -o gauss_clamping -t none --no_intermediate_results     --max_texture_size=8192
Load and prepare mesh:
Reading PLY: 12612 verts... done.
Warning: Zero-length normals detected: 0 face normals, 12612 vertex normals
Generating texture views:
NVM: Loading file...
NVM: Number of views: 350
NVM: Number of features: 206383

Loading 100%... done. (Took 23.872s)
Building adjacency graph:
0 total edges.
View selection:
Building BVH from 0 faces... terminate called after throwing an instance of 'std::length_error'
what():  vector::_M_default_append
Aborted (core dumped)

===== Dumping Info for Geeks (developers need this to fix bugs) =====
Child returned 134
Traceback (most recent call last):
File "/code/stages/odm_app.py", line 82, in execute
self.first_stage.run()
File "/code/opendm/types.py", line 438, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 438, in run
self.next_stage.run(outputs)
File "/code/opendm/types.py", line 438, in run
self.next_stage.run(outputs)
[Previous line repeated 4 more times]
File "/code/opendm/types.py", line 417, in run
self.process(self.args, outputs)
File "/code/stages/mvstex.py", line 119, in process
system.run('"{bin}" "{nvm_file}" "{model}" "{out_dir}" '
File "/code/opendm/system.py", line 112, in run
raise SubprocessException("Child returned {}".format(retcode), retcode)
opendm.system.SubprocessException: Child returned 134

===== Done, human-readable information to follow... =====

[ERROR]   Uh oh! Processing stopped because of strange values in the reconstruction. This is often a sign that the input data has some issues or the software cannot deal with it. Have you followed best practices for data acquisition? See https://docs.opendronemap.org/flying/

****************************************
### How did you install WebODM (docker, installer, etc.)?
https://wiki.openstreetmap.org/wiki/WebODM

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
Windows 11, Firefox

### What is the problem?

Some abort error I don't quite understand

### How can we reproduce this? 
Well I've seen this error now a few times, when there's GCP on one side of the aerial photos but the other side has nothing..

**Comment by duiveldoder** [comment]
huh? I just need info on the report itself and it's automatically closed? I don't understand
