### ISSUE TITLE
node fails to start with TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by kpoman** [OpenDroneMap/WebODM#1452]
### How did you install WebODM (docker, installer, etc.)?
docker images

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
Google chrome, Windows 10 pro

### What is the problem?

The web app starts fine, however, the node fails with some nodejs error:

```
node-odm-1  | /var/www/config.js:21
node-odm-1  | let argv = require('minimist')(process.argv.slice(2));
node-odm-1  |                               ^
node-odm-1  |
node-odm-1  | TypeError: require(...) is not a function
node-odm-1  |     at Object.<anonymous> (/var/www/config.js:21:31)
node-odm-1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
node-odm-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
node-odm-1  |     at Module.load (internal/modules/cjs/loader.js:950:32)
node-odm-1  |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
node-odm-1  |     at Module.require (internal/modules/cjs/loader.js:974:19)
node-odm-1  |     at require (internal/modules/cjs/helpers.js:101:18)
node-odm-1  |     at Object.<anonymous> (/var/www/index.js:21:16)
node-odm-1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
node-odm-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
node-odm-1 exited with code 1

```
So, node is offline and refuses to be started. 
### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

I downloaded from scratch and installed latest git client and docker apps

**Comment by kpoman** [comment]
After deleting the image, redownloading it and restarting, it fails in the same way:

```
$ ./webodm.sh start
Checking for docker...   OK
Checking for docker-compose...  OK
Starting WebODM...

Using the following environment:
================================
Host: localhost
Port: 8000
Media directory: appmedia
Postgres DB directory: dbdata
SSL: NO
SSL key:
SSL certificate:
SSL insecure port redirect: 80
Celery Broker: redis://broker
Default Nodes: 1
Settings:
Worker memory limit:
Worker cpus limit:
================================
Make sure to issue a ./webodm.sh down if you decide to change the environment.

docker-compose -f docker-compose.yml -f docker-compose.nodeodm.yml up --scale node-odm=1
 node-odm Pulling
 6f172cdbcbef Already exists
 1ceb7add7f88 Already exists
 8554f052ebbe Already exists
 7271cd6b4eb9 Already exists
 b46905e67503 Already exists
 26b2d1fbca59 Already exists
 f34e6b3c6463 Already exists
 12c093045606 Already exists
 56965d0a0aab Already exists
 2c9f41f9e7f2 Already exists
 4f4fb700ef54 Already exists
 4530cba6f703 Already exists
 b9f8fc79b5c8 Already exists
 node-odm Pulled
 Container db  Created
 Container webodm-node-odm-1  Created
 Container broker  Created
 Container worker  Created
 Container webapp  Created
Attaching to broker, db, webapp, node-odm-1, worker
node-odm-1  | /var/www/config.js:21
node-odm-1  | let argv = require('minimist')(process.argv.slice(2));
node-odm-1  |                               ^
node-odm-1  |
node-odm-1  | TypeError: require(...) is not a function
node-odm-1  |     at Object.<anonymous> (/var/www/config.js:21:31)
node-odm-1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
node-odm-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
node-odm-1  |     at Module.load (internal/modules/cjs/loader.js:950:32)
node-odm-1  |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
node-odm-1  |     at Module.require (internal/modules/cjs/loader.js:974:19)
node-odm-1  |     at require (internal/modules/cjs/helpers.js:101:18)
node-odm-1  |     at Object.<anonymous> (/var/www/index.js:21:16)
node-odm-1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
node-odm-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
broker      | 1:C 28 Dec 2023 21:50:59.358 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
broker      | 1:C 28 Dec 2023 21:50:59.358 # Redis version=7.0.10, bits=64, commit=00000000, modified=0, pid=1, just started
broker      | 1:C 28 Dec 2023 21:50:59.358 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
broker      | 1:M 28 Dec 2023 21:50:59.359 * monotonic clock: POSIX clock_gettime
broker      | 1:M 28 Dec 2023 21:50:59.359 * Running mode=standalone, port=6379.
broker      | 1:M 28 Dec 2023 21:50:59.359 # Server initialized
broker      | 1:M 28 Dec 2023 21:50:59.359 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
broker      | 1:M 28 Dec 2023 21:50:59.360 * Loading RDB produced by version 7.0.10
broker      | 1:M 28 Dec 2023 21:50:59.360 * RDB age 1563 seconds
broker      | 1:M 28 Dec 2023 21:50:59.360 * RDB memory usage when created 2.39 Mb
broker      | 1:M 28 Dec 2023 21:50:59.360 * Done loading RDB, keys loaded: 6, keys expired: 1.
broker      | 1:M 28 Dec 2023 21:50:59.360 * DB loaded from disk: 0.000 seconds
broker      | 1:M 28 Dec 2023 21:50:59.360 * Ready to accept connections
db          |
db          | PostgreSQL Database directory appears to contain a database; Skipping initialization
db          |
db          | LOG:  database system was interrupted; last known up at 2023-12-28 21:34:53 UTC
worker      | psql: error: FATAL:  the database system is starting up
db          | FATAL:  the database system is starting up
worker      | Postgres is unavailable - sleeping
node-odm-1 exited with code 0
db          | LOG:  database system was not properly shut down; automatic recovery in progress
db          | LOG:  redo starts at 0/2072350
db          | LOG:  invalid record length at 0/2073E80
db          | LOG:  redo done at 0/2073E58
db          | LOG:  last completed transaction was at log time 2023-12-28 21:35:12.99979+00
node-odm-1  | /var/www/config.js:21
node-odm-1  | let argv = require('minimist')(process.argv.slice(2));
node-odm-1  |                               ^
node-odm-1  |
node-odm-1  | TypeError: require(...) is not a function
node-odm-1  |     at Object.<anonymous> (/var/www/config.js:21:31)
node-odm-1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
node-odm-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
node-odm-1  |     at Module.load (internal/modules/cjs/loader.js:950:32)
node-odm-1  |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
node-odm-1  |     at Module.require (internal/modules/cjs/loader.js:974:19)
node-odm-1  |     at require (internal/modules/cjs/helpers.js:101:18)
node-odm-1  |     at Object.<anonymous> (/var/www/index.js:21:16)
node-odm-1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
node-odm-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
db          | LOG:  MultiXact member wraparound protections are now enabled
db          | LOG:  database system is ready to accept connections
db          | LOG:  autovacuum launcher started
webapp      | Postgres is up - executing command
webapp      | wait-for-it.sh: waiting for broker:6379 without a timeout
webapp      | wait-for-it.sh: broker:6379 is available after 0 seconds
webapp      |
webapp      |  _       __     __    ____  ____  __  ___
webapp      | | |     / /__  / /_  / __ \/ __ \/  |/  /
webapp      | | | /| / / _ \/ __ \/ / / / / / / /|_/ /
webapp      | | |/ |/ /  __/ /_/ / /_/ / /_/ / /  / /
webapp      | |__/|__/\___/_.___/\____/_____/_/  /_/
webapp      |
webapp      |
webapp      | Checking python version... 3.x, good!
webapp      | Checking GDAL version... GDAL 3.2.2, released 2021/03/05, excellent!
webapp      | Running migrations
worker      | Postgres is up - executing command
worker      | wait-for-it.sh: waiting for broker:6379 without a timeout
worker      | wait-for-it.sh: broker:6379 is available after 1 seconds
worker      | wait-for-it.sh: waiting for webapp:8000 without a timeout
node-odm-1 exited with code 0
node-odm-1  | /var/www/config.js:21
node-odm-1  | let argv = require('minimist')(process.argv.slice(2));
node-odm-1  |                               ^
node-odm-1  |
node-odm-1  | TypeError: require(...) is not a function
node-odm-1  |     at Object.<anonymous> (/var/www/config.js:21:31)
node-odm-1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
node-odm-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
node-odm-1  |     at Module.load (internal/modules/cjs/loader.js:950:32)
node-odm-1  |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
node-odm-1  |     at Module.require (internal/modules/cjs/loader.js:974:19)
node-odm-1  |     at require (internal/modules/cjs/helpers.js:101:18)
node-odm-1  |     at Object.<anonymous> (/var/www/index.js:21:16)
node-odm-1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
node-odm-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
node-odm-1 exited with code 0
node-odm-1  | /var/www/config.js:21
node-odm-1  | let argv = require('minimist')(process.argv.slice(2));
node-odm-1  |                               ^
node-odm-1  |
node-odm-1  | TypeError: require(...) is not a function
node-odm-1  |     at Object.<anonymous> (/var/www/config.js:21:31)
node-odm-1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
node-odm-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
node-odm-1  |     at Module.load (internal/modules/cjs/loader.js:950:32)
node-odm-1  |     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
node-odm-1  |     at Module.require (internal/modules/cjs/loader.js:974:19)
node-odm-1  |     at require (internal/modules/cjs/helpers.js:101:18)
node-odm-1  |     at Object.<anonymous> (/var/www/index.js:21:16)
node-odm-1  |     at Module._compile (internal/modules/cjs/loader.js:1085:14)
node-odm-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
node-odm-1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
 Container webapp  Stopping
 Container webodm-node-odm-1  Killing
 Container worker  Killing
 Container webapp  Killing
 Container db  Killing
 Container broker  Killing
 Container webodm-node-odm-1  Killed
time="2023-12-28T18:51:04-03:00" level=error msg="got 3 SIGTERM/SIGINTs, forcing shutdown"

```

**Comment by kpoman** [comment]
From what I see, there is a bug in this line:
`let argv = require('minimist')(process.argv.slice(2));
`
which should be:
```

var minimist = require('minimist');
let argv = minimist(process.argv.slice(2));
```

Could you please fix the image?
Thank you

**Comment by pierotofy** [comment]
Moving the conversation over to https://github.com/OpenDroneMap/NodeODM/issues/211
