### ISSUE TITLE
Update Django Framework from 2.2.27 to 4.2 LTS

### ISSUE THREAD

**Issue by chris-bateman** [OpenDroneMap/WebODM#1471]
### How did you install WebODM (docker, installer, etc.)?

N/A

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

N/A

### What is the problem?

Django framework is EOL.  WebODM uses 2.2.27 and the current LTS is 4.2
Placeholder issue to begin discussion on upgrading the framework.

### How can we reproduce this? (What steps trigger the problem? What parameters are you using for processing? Include screenshots. If you are having issues processing a dataset, you must include a copy of your dataset uploaded on Dropbox, Google Drive or https://dronedb.app)

Review Django version here - https://github.com/OpenDroneMap/WebODM/blob/8150b822d9851fca434a5dedbdb5c5e1b3da2c3d/requirements.txt#L7

4.2 LTS makes sense support-wise, but v5 is also out.

**Comment by chris-bateman** [comment]
EOL notes - https://www.djangoproject.com/download/ and https://endoflife.date/django

**Comment by Saijin-Naib** [comment]
Do you know of any gotchas? API breaks? 

Keeping current on supported dependencies would be wonderful.

**Comment by chris-bateman** [comment]
So this doco covers the process - https://docs.djangoproject.com/en/5.0/howto/upgrade-version/

Example incompatible notes - https://docs.djangoproject.com/en/5.0/releases/4.2/#backwards-incompatible-changes-in-4-2

And a good list here as well - https://docs.djangoproject.com/en/5.0/internals/deprecation/

**Comment by chris-bateman** [comment]
I started to make a little progress on this.  I am playing dependency wack a mole.
So with that in mind it might be time to audit the current modules located in this file - 
https://github.com/OpenDroneMap/WebODM/blob/master/requirements.txt

The main focus is identifying packages that are deprecated/abandoned with no clear support from their maintainer/community.
Some have suitable alternatives noted in their doco but others will require some research to find a suitable replacement.

**django-guardian**
![image](https://github.com/OpenDroneMap/WebODM/assets/12206103/6e8d202d-9f99-4e13-a475-52edd01e7b9b)

**rfc3987** - Github repo was archived on the 12th Jan 2024 but moved to a new repo recently.
https://codeberg.org/atufi/rfc3987/
![image](https://github.com/OpenDroneMap/WebODM/assets/12206103/64541de4-0683-454e-bb73-470c7e5d1f0d)

**djangorestframework-jwt** - Github archived 
Alternatives - https://github.com/jpadilla/django-rest-framework-jwt/issues/484
![image](https://github.com/OpenDroneMap/WebODM/assets/12206103/41e44028-21c8-4ba5-9d2f-41aed1997428)

**itypes** - Github archived
![image](https://github.com/OpenDroneMap/WebODM/assets/12206103/811a5347-334c-4449-a517-d02f1f9136ab)

**django-rest-framework-guardian** 
![image](https://github.com/OpenDroneMap/WebODM/assets/12206103/79d5397f-9067-445a-ad9c-5703a3cbb9ca)

**strict-rfc3339**
![image](https://github.com/OpenDroneMap/WebODM/assets/12206103/74f24837-3a90-46c2-8ad5-ca4aa7bab0d2)

**openapi-codec** - Github archived
![image](https://github.com/OpenDroneMap/WebODM/assets/12206103/0daa821a-b6d5-4dbe-bad7-f4140f320f3d)

**django-codemirror2** - After 7 years of no activity has had a few updates this year. 
![image](https://github.com/OpenDroneMap/WebODM/assets/12206103/02d20ba8-701f-42e0-86e7-e56cda324590)

**piexif**
![image](https://github.com/OpenDroneMap/WebODM/assets/12206103/9d7d427c-73ee-4e08-9dca-f8079923825c)

**Comment by smathermather** [comment]
This is great Chris. Anything you need to help, e.g. identifying alternatives? I would say, for anything that has a known upgrade path, feel free to upgrade and test, and send me a relevant repo to review and I'm happy to run in production on my end and help find any issues.

**Comment by NtskwK** [comment]
> Do you know of any gotchas? API breaks?
> 
> Keeping current on supported dependencies would be wonderful.

Support for the previous LTS, Django 3.2, will end in April 2024. Then, [upstream support for PostgreSQL 11 ends in November 2023. Django 4.2 supports PostgreSQL 12 and higher.](https://docs.djangoproject.com/en/5.0/releases/4.2/#dropped-support-for-postgresql-11)

But [the EOL of PostgreSQL 12  is coming soon in November 14, 2024.](https://www.postgresql.org/support/versioning/)

It may be a lot of challenges.

**Comment by NtskwK** [comment]
Hello everyone!

Great news! The migration work has made some progress, including Django 4.2 LTS, PostgreSQL 16, and more. We still need to conduct further testing on functions. Could you create a new branch for this purpose, please. I will creat a PR and advance the work to the next stage.

Thank you! @Saijin-Naib @smathermather

**Comment by smathermather** [comment]
I defer to Piero on workflow, but we typically just keep the main branch except for hot fixes, and then merge from branches on forks when testing is complete. If you let me know what fork/branch you have for testing, I can build and test as a start.

**Comment by NtskwK** [comment]
I have solved a part compatibility problems to sure it can work in the development environment.

But there are also many different from [django-rest-framework-jwt](https://github.com/jpadilla/django-rest-framework-jwt) to [djangorestframework-simplejwt](https://github.com/jazzband/djangorestframework-simplejwt). So it can not pass the test.

But I don't really understand about auth function. I'm sorry.

**Comment by NtskwK** [comment]
> That is fantastic news! Thanks for continuing on this path.
> 
> I defer to Piero on workflow, but we typically just keep the main branch except for hot fixes, and then merge from branches on forks when testing is complete. If you let me know what fork/branch you have for testing, I can build and test as a start.

My apologies. I noticed that there is a actions for Build Docker Image and Public. I don't know whether it can bring dangers to other users with some **Breaking change**. In my opinions that we should be more careful. 

If you think it doesn't matter, that I will do it soon.

**Comment by smathermather** [comment]
Thanks for the pull request!

We can run workflows on pull requests without merging, they just don't run by default. Once the pull request is far enough along and reviewed, I would expect we'll also test it in a workflow before merging.

**Comment by NtskwK** [comment]
#1543 @pierotofy 
There is a problem with the recover database migrations.

> django.db.utils.ProgrammingError: type "raster" does not exist
> LINE 1: ...d_control_points" varchar(100) NULL, "orthophoto" raster NUL...

I found the field orthophoto in models.Task was been add in 2016, then deleted in 2017. 

>
```python
 79 |                 ('orthophoto', django.contrib.gis.db.models.RasterField(blank=True, help_text='Orthophoto created by OpenDroneMap', null=True, srid=4326)),
```

>app\migrations\0004_auto_20170707_1014.py
```python
    operations = [
        migrations.RemoveField(
            model_name='task',
            name='orthophoto',
        ),
```

`python manage.py migrate` will perform all the operations in turn. It could have to remove database migrations files if we don't change `app\migrations\0001_initial.py` with create `postgis_raster` extension.
[If you plan to use PostGIS raster functionality, you should also activate the postgis_raster extension. ](https://docs.djangoproject.com/en/5.1/ref/contrib/gis/install/postgis/#creating-a-spatial-database)

**Comment by NtskwK** [comment]
TODO: update Ubuntu to 24.04 LTS or 22.04 LTS

I'll have a try.

**Comment by NtskwK** [comment]
> sed: can't read /usr/include/proj_api.h: No such file or directory

The behavior of `libproj-dev ` did not match expectations on 24.04 even 22.04. What is the purpose of this command? Is this necessary? @pierotofy @chris-bateman #1545 

```dockerfile
	tar -zxf postgis-$POSTGIS_VERSION.tar.gz; \
	sed -i 's/#error.*/#define ACCEPT_USE_OF_DEPRECATED_PROJ_API_H 1/' /usr/include/proj_api.h; \
        cd /staging/postgis-$POSTGIS_VERSION; \
	./configure --with-pgconfig=/usr/local/pgsql/bin/pg_config --with-gdalconfig=/usr/bin/gdal-config > /dev/null; \
```

**Comment by NtskwK** [comment]
```
worker      | [2024-09-01 12:31:09,435: ERROR/ForkPoolWorker-13] worker.tasks.process_task[7d945936-a740-43db-9ec3-1f65338a9cb2]: Uncaught error! This is potentially bad. Please report it 
to http://github.com/OpenDroneMap/WebODM/issues: Signal.__init__() got an unexpected keyword argument 'providing_args' Traceback (most recent call last):
worker      |   File "/webodm/worker/tasks.py", line 143, in process_task
worker      |     task.process()
worker      |   File "/webodm/app/models/task.py", line 629, in process
worker      |     resized_images = self.resize_images()
worker      |   File "/webodm/app/models/task.py", line 1154, in resize_images
worker      |     from app.plugins import signals as plugin_signals
worker      |   File "/webodm/app/plugins/signals.py", line 3, in <module>
worker      |     task_completed = django.dispatch.Signal(providing_args=["task_id"])
worker      | TypeError: Signal.__init__() got an unexpected keyword argument 'providing_args'
```

**Comment by NtskwK** [comment]
@pierotofy  Django 4.2 only supports PostgreSQL 12 and higher. Whether to need to continue to push the work, but more conservative.
