### ISSUE TITLE
Histogram in layer list does not change if min/max fields are changed

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#1556]
* Open a map
 * Change the min/max fields from layer list
 * Witness:

MapView-db730c7529e8bf17012a.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'factor')
    at MapView-db730c7529e8bf17012a.js:2:902330
    at Object.g [as unitBackward] (MapView-db730c7529e8bf17012a.js:2:902698)
    at MapView-db730c7529e8bf17012a.js:2:853596
    at Object.s (MapView-db730c7529e8bf17012a.js:2:629255)
    at p (MapView-db730c7529e8bf17012a.js:2:629398)
    at MapView-db730c7529e8bf17012a.js:2:629544
    at g (MapView-db730c7529e8bf17012a.js:2:629630)
    at oe (MapView-db730c7529e8bf17012a.js:2:645097)
    at re (MapView-db730c7529e8bf17012a.js:2:644907)
    at ae (MapView-db730c7529e8bf17012a.js:2:645263)

**Comment by smathermather** [comment]
Ah, should have reported this. Noticed it on my phone, but I'm always using an odd browser so I assumed it was just me.
