### ISSUE TITLE
FileNotFoundError after uploads with gunicorn

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#200]
Django reports the following error (many times) after a successful file upload when running via gunicorn:
```
webapp | FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpeeujj1ph.upload'
webapp | Exception ignored in: <bound method _TemporaryFileCloser.del of <tempfile._TemporaryFileCloser object at 0x7f89f4289e48>>
webapp | Traceback (most recent call last):
webapp | File "/usr/local/lib/python3.5/tempfile.py", line 450, in del
webapp | self.close()
webapp | File "/usr/local/lib/python3.5/tempfile.py", line 446, in close
webapp | unlink(self.name)
webapp | FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp3ri61zpn.upload'
```

**Comment by pierotofy** [comment]
The warning is due to Python's tempfile.py attempt to delete the temporary file at its original location, but failing to do so, because it has already been moved to the new location under app/media. Since the exception is thrown in the __del__() destructor, the exception is ignored. This does not happen on the django dev server because the garbage collector never gets invoked.

https://docs.python.org/2/reference/datamodel.html#object.__del__

**Comment by pierotofy** [comment]
This is really a Python core issue, so there's nothing I can do to fix this. I will mitigate it by increasing `FILE_UPLOAD_MAX_MEMORY_SIZE` to 4.5 mb (the typical size of a drone image), which will cause Django to store the file in memory instead of using temporary files before moving them to app/media. This should reduce the frequency of the message.
