### ISSUE TITLE
Docker build fails because of SECRET_KEY

### ISSUE THREAD

**Issue by wasi** [OpenDroneMap/WebODM#252]
The build (docker build .) fails with the following exception. I fixed it with setting SECRET_KEY with the just generated key instead of importing it. I'll open a PR.

```
Traceback (most recent call last):
  File "/webodm/webodm/settings.py", line 28, in <module>
    from .secret_key import SECRET_KEY
ImportError: No module named 'webodm.secret_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/webodm/webodm/settings.py", line 39, in <module>
    from .secret_key import SECRET_KEY
ImportError: No module named 'webodm.secret_key'
The command '/bin/sh -c python manage.py collectstatic --noinput' returned a non-zero code: 1

```

**Comment by pierotofy** [comment]
Merged, thank you for the PR!
