### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by geoglrb** [OpenDroneMap/WebODM#254]
Reporting as requested by the below...
```
webapp        | ERROR Uncaught error! This is potentially bad. Please report it to http://github.com/OpenDroneMap/WebODM/issues: FATAL:  the database system is shutting down
webapp        |  Traceback (most recent call last):
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 178, in __get__
webapp        |     rel_obj = getattr(instance, self.cache_name)
webapp        | AttributeError: 'Task' object has no attribute '_processing_node_cache'
webapp        |
webapp        | During handling of the above exception, another exception occurred:
webapp        |
webapp        | Traceback (most recent call last):
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
webapp        |     self.connect()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
webapp        |     self.connection = self.get_new_connection(conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
webapp        |     connection = Database.connect(**conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
webapp        |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
webapp        | psycopg2.OperationalError: FATAL:  the database system is shutting down
webapp        |
webapp        |
webapp        | The above exception was the direct cause of the following exception:
webapp        |
webapp        | Traceback (most recent call last):
webapp        |   File "/webodm/app/scheduler.py", line 54, in process
webapp        |     task.process()
webapp        |   File "/webodm/app/models/task.py", line 226, in process
webapp        |     if self.processing_node is None:
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 184, in __get__
webapp        |     rel_obj = self.get_object(instance)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 159, in get_object
webapp        |     return qs.get(self.field.get_reverse_related_filter(instance))
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 374, in get
webapp        |     num = len(clone)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 232, in __len__
webapp        |     self._fetch_all()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1103, in _fetch_all
webapp        |     self._result_cache = list(self._iterable_class(self))
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
webapp        |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 874, in execute_sql
webapp        |     cursor = self.connection.cursor()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 254, in cursor
webapp        |     return self._cursor()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 229, in _cursor
webapp        |     self.ensure_connection()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
webapp        |     self.connect()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
webapp        |     six.reraise(dj_exc_type, dj_exc_value, traceback)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
webapp        |     raise value.with_traceback(tb)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
webapp        |     self.connect()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
webapp        |     self.connection = self.get_new_connection(conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
webapp        |     connection = Database.connect(**conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
webapp        |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
webapp        | django.db.utils.OperationalError: FATAL:  the database system is shutting down
webapp        |
```

**Comment by geoglrb** [comment]
@pierotofy 
I was working in other windows at the time that the above error came back, and I'm not even entirely sure when it happened. I did have a moment when, at a minimum, all user-level processes seemed to crash and I was returned to the MacOS login--that could have been a full reboot, though it was pretty quick. It was very unusual and strange for me. I'm not sure how that moment does or doesn't relate. I had two projects reconstructing models in WebODM at the time. I received other errors as well, apologies. Here is a longer set of outputs that include the above snippet and go beyond it:
```
webapp        | INFO Acquiring lock: Task [Task of 2017-07-28T00:17:25.518Z] (4)
webapp        | INFO Acquiring lock: Task [Task of 2017-07-28T00:17:04.417Z] (3)
db            | LOG:  received smart shutdown request
db            | LOG:  autovacuum launcher shutting down
webapp        | INFO Acquiring lock: Task [Task of 2017-07-28T00:17:25.518Z] (4)
node-odm-1    | info: Closing server
webapp        | INFO Acquiring lock: Task [Task of 2017-07-28T00:17:04.417Z] (3)
node-odm-1    | info: Exiting...
db            | FATAL:  the database system is shutting down
db            | FATAL:  the database system is shutting down
db            | FATAL:  the database system is shutting down
db            | FATAL:  the database system is shutting down
webapp        | ERROR Uncaught error! This is potentially bad. Please report it to http://github.com/OpenDroneMap/WebODM/issues: FATAL:  the database system is shutting down
webapp        |  Traceback (most recent call last):
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 178, in __get__
webapp        |     rel_obj = getattr(instance, self.cache_name)
webapp        | AttributeError: 'Task' object has no attribute '_processing_node_cache'
webapp        |
webapp        | During handling of the above exception, another exception occurred:
webapp        |
webapp        | Traceback (most recent call last):
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
webapp        |     self.connect()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
webapp        |     self.connection = self.get_new_connection(conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
webapp        |     connection = Database.connect(**conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
webapp        |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
webapp        | psycopg2.OperationalError: FATAL:  the database system is shutting down
webapp        |
webapp        |
webapp        | The above exception was the direct cause of the following exception:
webapp        |
webapp        | Traceback (most recent call last):
webapp        |   File "/webodm/app/scheduler.py", line 54, in process
webapp        |     task.process()
webapp        |   File "/webodm/app/models/task.py", line 226, in process
webapp        |     if self.processing_node is None:
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 184, in __get__
webapp        |     rel_obj = self.get_object(instance)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 159, in get_object
webapp        |     return qs.get(self.field.get_reverse_related_filter(instance))
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 374, in get
webapp        |     num = len(clone)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 232, in __len__
webapp        |     self._fetch_all()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1103, in _fetch_all
webapp        |     self._result_cache = list(self._iterable_class(self))
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
webapp        |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 874, in execute_sql
webapp        |     cursor = self.connection.cursor()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 254, in cursor
webapp        |     return self._cursor()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 229, in _cursor
webapp        |     self.ensure_connection()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
webapp        |     self.connect()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
webapp        |     six.reraise(dj_exc_type, dj_exc_value, traceback)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
webapp        |     raise value.with_traceback(tb)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
webapp        |     self.connect()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
webapp        |     self.connection = self.get_new_connection(conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
webapp        |     connection = Database.connect(**conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
webapp        |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
webapp        | django.db.utils.OperationalError: FATAL:  the database system is shutting down
webapp        |
webapp        |
webapp        | ERROR Uncaught error! This is potentially bad. Please report it to http://github.com/OpenDroneMap/WebODM/issues: FATAL:  the database system is shutting down
webapp        |  Traceback (most recent call last):
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 178, in __get__
webapp        |     rel_obj = getattr(instance, self.cache_name)
webapp        | AttributeError: 'Task' object has no attribute '_processing_node_cache'
webapp        |
webapp        | During handling of the above exception, another exception occurred:
webapp        |
webapp        | Traceback (most recent call last):
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
webapp        |     self.connect()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
webapp        |     self.connection = self.get_new_connection(conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
webapp        |     connection = Database.connect(**conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
webapp        |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
webapp        | psycopg2.OperationalError: FATAL:  the database system is shutting down
webapp        |
webapp        |
webapp        | The above exception was the direct cause of the following exception:
webapp        |
webapp        | Traceback (most recent call last):
webapp        |   File "/webodm/app/scheduler.py", line 54, in process
webapp        |     task.process()
webapp        |   File "/webodm/app/models/task.py", line 226, in process
webapp        |     if self.processing_node is None:
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 184, in __get__
webapp        |     rel_obj = self.get_object(instance)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 159, in get_object
webapp        |     return qs.get(self.field.get_reverse_related_filter(instance))
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 374, in get
webapp        |     num = len(clone)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 232, in __len__
webapp        |     self._fetch_all()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1103, in _fetch_all
webapp        |     self._result_cache = list(self._iterable_class(self))
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 53, in __iter__
webapp        |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 874, in execute_sql
webapp        |     cursor = self.connection.cursor()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 254, in cursor
webapp        |     return self._cursor()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 229, in _cursor
webapp        |     self.ensure_connection()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
webapp        |     self.connect()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
webapp        |     six.reraise(dj_exc_type, dj_exc_value, traceback)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
webapp        |     raise value.with_traceback(tb)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
webapp        |     self.connect()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
webapp        |     self.connection = self.get_new_connection(conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
webapp        |     connection = Database.connect(**conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
webapp        |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
webapp        | django.db.utils.OperationalError: FATAL:  the database system is shutting down
webapp        |
webapp        |
webapp        | ERROR Job "background.<locals>.wrapper (trigger: interval[0:00:05], next run at: 2017-07-28 23:55:32 UTC)" raised an exception
webapp        | Traceback (most recent call last):
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
webapp        |     self.connect()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
webapp        |     self.connection = self.get_new_connection(conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
webapp        |     connection = Database.connect(**conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
webapp        |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
webapp        | psycopg2.OperationalError: FATAL:  the database system is shutting down
webapp        |
webapp        |
webapp        | The above exception was the direct cause of the following exception:
webapp        |
webapp        | Traceback (most recent call last):
webapp        |   File "/usr/local/lib/python3.5/site-packages/apscheduler/executors/base.py", line 125, in run_job
webapp        |     retval = job.func(*job.args, **job.kwargs)
webapp        |   File "/webodm/app/background.py", line 39, in wrapper
webapp        |     return func(*args, **kwargs)
webapp        |   File "/webodm/app/scheduler.py", line 68, in process_pending_tasks
webapp        |     pool.map(process, tasks, chunksize=1)
webapp        |   File "/usr/local/lib/python3.5/multiprocessing/pool.py", line 260, in map
webapp        |     return self._map_async(func, iterable, mapstar, chunksize).get()
webapp        |   File "/usr/local/lib/python3.5/multiprocessing/pool.py", line 608, in get
webapp        |     raise self._value
webapp        |   File "/usr/local/lib/python3.5/multiprocessing/pool.py", line 119, in worker
webapp        |     result = (True, func(*args, **kwds))
webapp        |   File "/usr/local/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
webapp        |     return list(map(*args))
webapp        |   File "/webodm/app/scheduler.py", line 62, in process
webapp        |     task.save()
webapp        |   File "/webodm/app/models/task.py", line 161, in save
webapp        |     self.full_clean()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 1226, in full_clean
webapp        |     self.clean_fields(exclude=exclude)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 1268, in clean_fields
webapp        |     setattr(self, f.attname, f.clean(raw_value, self))
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 602, in clean
webapp        |     self.validate(value, model_instance)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related.py", line 932, in validate
webapp        |     if not qs.exists():
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 668, in exists
webapp        |     return self.query.has_results(using=self.db)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/query.py", line 517, in has_results
webapp        |     return compiler.has_results()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 845, in has_results
webapp        |     return bool(self.execute_sql(SINGLE))
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 874, in execute_sql
webapp        |     cursor = self.connection.cursor()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 254, in cursor
webapp        |     return self._cursor()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 229, in _cursor
webapp        |     self.ensure_connection()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
webapp        |     self.connect()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
webapp        |     six.reraise(dj_exc_type, dj_exc_value, traceback)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
webapp        |     raise value.with_traceback(tb)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
webapp        |     self.connect()
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/base.py", line 189, in connect
webapp        |     self.connection = self.get_new_connection(conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
webapp        |     connection = Database.connect(**conn_params)
webapp        |   File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
webapp        |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
webapp        | django.db.utils.OperationalError: FATAL:  the database system is shutting down
webapp        |
Unexpected API error for node-odm-1 (HTTP code 502)
Response body:
Bad response from Docker engine

Unexpected API error for db (HTTP code 502)
Response body:
Bad response from Docker engine

Unexpected API error for webapp (HTTP code 502)
Response body:
Bad response from Docker engine
```

**Comment by pierotofy** [comment]
Sorry for the late reply, it's quite possible that MacOS ran out of memory and started killing processes to free up memory, thus causing the database to shutdown and causing the error message in the log.

I would say this is normal, and catching the error would simply give us a prettier error message without the stack trace.
