### ISSUE TITLE
Processing of lots of images fails in timeout

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#44]
File "C:\Users\piero\Desktop\WebODM\nodeodm\api_client.py", line 64, in new_task
    data={'name': name, 'options': json.dumps(options)}).json()
  File "C:\Users\piero\webodm\lib\site-packages\requests\api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\piero\webodm\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\piero\webodm\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\piero\webodm\lib\site-packages\requests\sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\piero\webodm\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond a

requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

**Comment by pierotofy** [comment]
To reproduce: start a task on WebODM, then kill the processing node in the middle of processing.

**Comment by pierotofy** [comment]
Reproduced it today also:

```
ERROR Uncaught error: HTTPConnectionPool(host='nodeodm.masseranolabs.com', port=80): Max retries exceeded with url: /task/87943212-eb60-4ea7-9cab-44b9b0dc9d53/output?line=303 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f12484d06d8>, 'Connection to nodeodm.masseranolabs.com timed out. (connect timeout=10)')) Traceback (most recent call last):
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 147, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.HTTPConnection object at 0x7f12484d06d8>, 'Connection to nodeodm.masseranolabs.com timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='nodeodm.masseranolabs.com', port=80): Max retries exceeded with url: /task/87943212-eb60-4ea7-9cab-44b9b0dc9d53/output?line=303 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f12484d06d8>, 'Connection to nodeodm.masseranolabs.com timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piero/Documents/WebODM/app/scheduler.py", line 82, in process
    task.process()
  File "/home/piero/Documents/WebODM/app/models.py", line 289, in process
    self.console_output += self.processing_node.get_task_console_output(self.uuid, current_lines_count)
  File "/home/piero/Documents/WebODM/nodeodm/models.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/piero/Documents/WebODM/nodeodm/models.py", line 124, in get_task_console_output
    result = api_client.task_output(uuid, line)
  File "/home/piero/Documents/WebODM/nodeodm/api_client.py", line 34, in task_output
    return requests.get(self.url('/task/{}/output?line={}').format(uuid, line), timeout=TIMEOUT).json()
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/piero/.envs/webodm/lib/python3.6/site-packages/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='nodeodm.masseranolabs.com', port=80): Max retries exceeded with url: /task/87943212-eb60-4ea7-9cab-44b9b0dc9d53/output?line=303 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f12484d06d8>, 'Connection to nodeodm.masseranolabs.com timed out. (connect timeout=10)'))
```

Processing gets stuck because a timeout throws an exception that is not caught, which leaves the task in an idle state.

**Comment by pierotofy** [comment]
Found the fault, the processing exception was caught, but the task was never release from its lock, which would prevent the processing to continue at the next tick.

A fix is available in the unittest branch and will be merged into master very soon (before end of the week).
