### ISSUE TITLE
WebpackError at /welcome/ after using Install Script Ubuntu 16.04

### ISSUE THREAD

**Issue by Wlanfr3ak** [OpenDroneMap/WebODM#538]
### How did you install WebODM? (Docker, natively, ...)?

WebODM Script for Ubuntu Server 16..04 LTS

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox 62 on Windows 10

### What is the problem?

WebODM Website didnt open after Installing WebODM with the Installer

### What should be the expected behavior?

Normally in my Tests i can now set a Password

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Try to install the Script on a 16.04.5 64Bit

Output: 

WebpackError at /welcome/

            ModuleBuildError in 
            Module build failed (from ./node_modules/extract-text-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (/usr/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.sassLoader (/webodm/node_modules/sass-loader/lib/loader.js:46:72)
    at runLoaders (/usr/lib/node_modules/webpack/lib/NormalModule.js:286:20)
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at process.nextTick (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
            

Request Method: 	GET
Request URL: 	http://<IP-Adress>/welcome/
Django Version: 	2.0.3
Exception Type: 	WebpackError
Exception Value: 	

            ModuleBuildError in 
            Module build failed (from ./node_modules/extract-text-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (/usr/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.sassLoader (/webodm/node_modules/sass-loader/lib/loader.js:46:72)
    at runLoaders (/usr/lib/node_modules/webpack/lib/NormalModule.js:286:20)
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at process.nextTick (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
            

Exception Location: 	/webodm/python3-venv/lib/python3.5/site-packages/webpack_loader/loader.py in get_bundle, line 97
Python Executable: 	/webodm/python3-venv/bin/python3
Python Version: 	3.5.2
Python Path: 	

['/webodm',
 '/webodm/python3-venv/bin',
 '/webodm/python3-venv/lib/python35.zip',
 '/webodm/python3-venv/lib/python3.5',
 '/webodm/python3-venv/lib/python3.5/plat-x86_64-linux-gnu',
 '/webodm/python3-venv/lib/python3.5/lib-dynload',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/webodm/python3-venv/lib/python3.5/site-packages',
 '/webodm']

Server time: 	Di, 16 Okt 2018 13:22:38 +0200

Error during template rendering

In template /webodm/app/templates/app/base.html, error at line 25
ModuleBuildError in Module build failed (from ./node_modules/extract-text-webpack-plugin/dist/loader.js): ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js): Error: Cannot find module 'node-sass' at Function.Module._resolveFilename (module.js:548:15) at Function.Module._load (module.js:475:25) at Module.require (module.js:597:17) at require (/usr/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20) at Object.sassLoader (/webodm/node_modules/sass-loader/lib/loader.js:46:72) at runLoaders (/usr/lib/node_modules/webpack/lib/NormalModule.js:286:20) at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:364:11 at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:230:18 at runSyncOrAsync (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:143:3) at iterateNormalLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:229:2) at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:202:4 at process.nextTick (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15) at _combinedTickCallback (internal/process/next_tick.js:132:7) at process._tickCallback (internal/process/next_tick.js:181:9)
15 	    <link href="{% static 'app/css/metisMenu.min.css' %}" rel="stylesheet">
16 	    <link href="{% static 'app/css/sb-admin-2.css' %}" rel="stylesheet">
17 	    {% block extra-headers %}{% endblock %}
18 	
19 	    <script src="{% static 'app/js/vendor/modernizr-2.8.3.min.js' %}"></script>
20 	    <script src="{% static 'app/js/vendor/es6-shim.min.js' %}"></script>
21 	    <script src="{% static 'app/js/vendor/jquery-1.11.2.min.js' %}"></script>
22 	    <script src="{% static 'app/js/vendor/system.js' %}"></script>
23 	
24 	    {% load render_bundle from webpack_loader %}
25 	    {% render_bundle 'main' %}
26 	
27 	    {% autoescape off %}
28 	    {% get_plugins_js_includes %}
29 	    {% get_plugins_css_includes %}
30 	    {% endautoescape %}
31 	
32 	    <title>{{title|default:"Login"}} - {{ SETTINGS.app_name }}</title>
33 	
34 	    {% compress css %}
35 	    <link rel="stylesheet" type="text/x-scss" href="{% static 'app/css/theme.scss' %}" />

Environment:

Request Method: GET
Request URL: http://<IP-Adress>/welcome/

Django Version: 2.0.3
Python Version: 3.5.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.gis',
 'django_filters',
 'guardian',
 'rest_framework',
 'rest_framework_nested',
 'webpack_loader',
 'corsheaders',
 'colorfield',
 'imagekit',
 'codemirror2',
 'compressor',
 'app',
 'nodeodm']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware']

Template error:
In template /webodm/app/templates/app/base.html, error at line 25
   
            ModuleBuildError in 
            Module build failed (from ./node_modules/extract-text-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (/usr/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.sassLoader (/webodm/node_modules/sass-loader/lib/loader.js:46:72)
    at runLoaders (/usr/lib/node_modules/webpack/lib/NormalModule.js:286:20)
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at process.nextTick (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
            
   15 :     <link href="{% static 'app/css/metisMenu.min.css' %}" rel="stylesheet">
   16 :     <link href="{% static 'app/css/sb-admin-2.css' %}" rel="stylesheet">
   17 :     {% block extra-headers %}{% endblock %}
   18 : 
   19 :     <script src="{% static 'app/js/vendor/modernizr-2.8.3.min.js' %}"></script>
   20 :     <script src="{% static 'app/js/vendor/es6-shim.min.js' %}"></script>
   21 :     <script src="{% static 'app/js/vendor/jquery-1.11.2.min.js' %}"></script>
   22 :     <script src="{% static 'app/js/vendor/system.js' %}"></script>
   23 : 
   24 :     {% load render_bundle from webpack_loader %}
   25 :      {% render_bundle 'main' %} 
   26 : 
   27 :     {% autoescape off %}
   28 :     {% get_plugins_js_includes %}
   29 :     {% get_plugins_css_includes %}
   30 :     {% endautoescape %}
   31 : 
   32 :     <title>{{title|default:"Login"}} - {{ SETTINGS.app_name }}</title>
   33 : 
   34 :     {% compress css %}
   35 :     <link rel="stylesheet" type="text/x-scss" href="{% static 'app/css/theme.scss' %}" />

Traceback:

File "/webodm/python3-venv/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/webodm/app/views/app.py" in welcome
  135.                       'firstuserform': fuf

File "/webodm/python3-venv/lib/python3.5/site-packages/django/shortcuts.py" in render
  36.     content = loader.render_to_string(template_name, context, request, using=using)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/loader.py" in render_to_string
  62.     return template.render(context, request)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/backends/django.py" in render
  61.             return self.template.render(context)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/base.py" in render
  175.                     return self._render(context)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/base.py" in _render
  167.         return self.nodelist.render(context)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/base.py" in render
  943.                 bit = node.render_annotated(context)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  910.             return self.render(context)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  155.             return compiled_parent._render(context)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/base.py" in _render
  167.         return self.nodelist.render(context)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/base.py" in render
  943.                 bit = node.render_annotated(context)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  910.             return self.render(context)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  155.             return compiled_parent._render(context)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/base.py" in _render
  167.         return self.nodelist.render(context)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/base.py" in render
  943.                 bit = node.render_annotated(context)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  910.             return self.render(context)

File "/webodm/python3-venv/lib/python3.5/site-packages/django/template/library.py" in render
  192.         output = self.func(*resolved_args, **resolved_kwargs)

File "/webodm/python3-venv/lib/python3.5/site-packages/webpack_loader/templatetags/webpack_loader.py" in render_bundle
  12.     tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)

File "/webodm/python3-venv/lib/python3.5/site-packages/webpack_loader/utils.py" in get_as_tags
  45.     bundle = _get_bundle(bundle_name, extension, config)

File "/webodm/python3-venv/lib/python3.5/site-packages/webpack_loader/utils.py" in _get_bundle
  23.     bundle = get_loader(config).get_bundle(bundle_name)

File "/webodm/python3-venv/lib/python3.5/site-packages/webpack_loader/loader.py" in get_bundle
  97.             raise WebpackError(error)

Exception Type: WebpackError at /welcome/
Exception Value: 
            ModuleBuildError in 
            Module build failed (from ./node_modules/extract-text-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (/usr/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.sassLoader (/webodm/node_modules/sass-loader/lib/loader.js:46:72)
    at runLoaders (/usr/lib/node_modules/webpack/lib/NormalModule.js:286:20)
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:202:4
    at process.nextTick (/usr/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by Wlanfr3ak** [comment]
Okay, i test it again and with the solution from the manual it works now.

**Comment by smathermather** [comment]
Excellent!
