### ISSUE TITLE
Fail when run start.sh

### ISSUE THREAD

**Issue by emiliobruno** [OpenDroneMap/WebODM#56]
Ciao Piero, 

Iḿ trying run WebODM from start.sh, but the following errors are listed : 

emilio@emilio-laptop:/opt/WebODM$ ./start.sh
Building asssets...
Hash: bcdca8dde46cb9609cf5
Version: webpack 1.13.3
Time: 52662ms
                       Asset     Size  Chunks             Chunk Names
main-bcdca8dde46cb9609cf5.js   1.9 MB       0  [emitted]  main
                css/main.css  41.3 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 255 hidden modules

WARNING in ./~/leaflet-measure/dist/leaflet-measure.js
Critical dependencies:
1:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/leaflet-measure/dist/leaflet-measure.js 1:113-120
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 6 hidden modules
Child extract-text-webpack-plugin:
        + 5 hidden modules
Child extract-text-webpack-plugin:
        + 14 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
Running migrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/WebODM/app/models.py", line 23, in <module>
    from nodeodm.models import ProcessingNode
  File "/opt/WebODM/nodeodm/models.py", line 10, in <module>
    from .api_client import ApiClient
  File "/opt/WebODM/nodeodm/api_client.py", line 9, in <module>
    from urllib.parse import urlunparse
ImportError: No module named parse
Unhandled exception in thread started by <function wrapper at 0x7fbf61b15848>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/WebODM/app/models.py", line 23, in <module>
    from nodeodm.models import ProcessingNode
  File "/opt/WebODM/nodeodm/models.py", line 10, in <module>
    from .api_client import ApiClient
  File "/opt/WebODM/nodeodm/api_client.py", line 9, in <module>
    from urllib.parse import urlunparse
ImportError: No module named parse

Grazie mille. 

Emilio Bruno

**Comment by pierotofy** [comment]
You have Python 2.7 installed. Per the [Readme](https://github.com/OpenDroneMap/WebODM/blob/master/README.md) instructions, you need to run WebODM using Python 3.5.
