### ISSUE TITLE
IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by sbonaime** [OpenDroneMap/WebODM#561]
### How did you install WebODM? (Docker, natively, ...)?
Docker 

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)
Firefox 63.03

### What is the problem?

WebODM crash with a very big project with 583 images (2.6Mo each)

Here is the end of the log:
```log
2018-11-28 14:38:00,120 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09968.jpg has 1 candidate matches
2018-11-28 14:38:01,269 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09969.jpg has 1 candidate matches
2018-11-28 14:38:02,378 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09970.jpg has 2 candidate matches
2018-11-28 14:38:03,506 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09971.jpg has 1 candidate matches
2018-11-28 14:38:04,628 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09972.jpg has 3 candidate matches
2018-11-28 14:38:05,788 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09973.jpg has 2 candidate matches
2018-11-28 14:38:06,985 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09974.jpg has 1 candidate matches
2018-11-28 14:38:08,271 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09975.jpg has 2 candidate matches
2018-11-28 14:38:09,518 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09976.jpg has 1 candidate matches
2018-11-28 14:38:10,670 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09977.jpg has 1 candidate matches
2018-11-28 14:38:11,893 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09978.jpg has 0 candidate matches
2018-11-28 14:38:13,087 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09979.jpg has 1 candidate matches
2018-11-28 14:38:14,312 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09980.jpg has 2 candidate matches
2018-11-28 14:38:15,497 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09981.jpg has 1 candidate matches
2018-11-28 14:38:16,734 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09982.jpg has 2 candidate matches
2018-11-28 14:38:18,003 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09983.jpg has 2 candidate matches
2018-11-28 14:38:19,263 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09984.jpg has 4 candidate matches
2018-11-28 14:38:20,484 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09985.jpg has 2 candidate matches
2018-11-28 14:38:21,682 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09986.jpg has 0 candidate matches
2018-11-28 14:38:22,965 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09987.jpg has 0 candidate matches
2018-11-28 14:38:24,196 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09988.jpg has 3 candidate matches
2018-11-28 14:38:25,417 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09989.jpg has 3 candidate matches
2018-11-28 14:38:26,656 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09990.jpg has 3 candidate matches
2018-11-28 14:38:27,806 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09991.jpg has 1 candidate matches
2018-11-28 14:38:28,951 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09992.jpg has 0 candidate matches
2018-11-28 14:38:30,128 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09993.jpg has 3 candidate matches
2018-11-28 14:38:31,311 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09994.jpg has 5 candidate matches
2018-11-28 14:38:32,485 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09995.jpg has 2 candidate matches
2018-11-28 14:38:33,702 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09996.jpg has 0 candidate matches
2018-11-28 14:38:34,904 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09997.jpg has 0 candidate matches
2018-11-28 14:38:36,104 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09998.jpg has 1 candidate matches
2018-11-28 14:38:37,241 DEBUG: SiteMbis-drone_09695.jpg - SiteMbis-drone_09999.jpg has 1 candidate matches
Traceback (most recent call last):
File "/code/SuperBuild/src/opensfm/bin/opensfm", line 34, in <module>
command.run(args)
File "/code/SuperBuild/src/opensfm/opensfm/commands/match_features.py", line 44, in run
parallel_map(match, args, processes)
File "/code/SuperBuild/src/opensfm/opensfm/context.py", line 38, in parallel_map
return list(e.map(func, args))
File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 786, in _chain_from_iterable_of_lists
for element in iterable:
File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 589, in result_iterator
yield future.result()
File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 433, in result
return self.__get_result()
File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 381, in __get_result
raise self._exception
IOError: [Errno 2] No such file or directory: u'/var/www/data/476ad4fc-a79d-4adf-a696-d29adcc3180b/opensfm/features/SiteMbis-drone_09577.jpg.npz'
Traceback (most recent call last):
File "/code/run.py", line 47, in <module>
plasm.execute(niter=1)
File "/code/scripts/run_opensfm.py", line 117, in process
(context.pyopencv_path, context.opensfm_path, tree.opensfm))
File "/code/opendm/system.py", line 34, in run
raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1
```

I tried to decrease the min-num-features from 8000 to 4000 but with no sucess
I also try with the following options

Options: dem-terrain-type: ComplexNonForest, dsm: true, rerun-from: dataset

I am using the latest WebODM  0.6.2

**Comment by pierotofy** [comment]
A lot has changed since 2 years ago; please try to process with the latest version of WebODM/ODM and see if the problem persists? :clinking_glasses: (if not, please re-open this issue).
