### ISSUE TITLE
Process Exited with Code 1 "Exception: Child Returned 134". memory or something else?

### ISSUE THREAD

**Issue by EricGamble** [OpenDroneMap/WebODM#622]
I am getting the dreaded code 1 error message when I try to process anything, I mean any number of photos.  I tried upping the Mi-Num to 12000 and 16000 with no luck. The only way I can get it to process is Ortho only and that result is "melting" at best and unusable. I am using the paid web Install of Web ODM using Firefox (whatever version is newest) on a windows 10 AMD Ryzen 5 1500 Quad core with just 16 gigs of memory.  I have tried kicking up my memory to 8 Gigs, but no luck.  Hoping for an easier solution?  Photos are min 75% overlap using a Typhoon H CGO3+. 

Log files
... output truncated at 500 lines ...
2019-02-12 17:23:39,779 DEBUG: Undistorting image YUN00659.jpg
2019-02-12 17:23:39,784 DEBUG: Undistorting image YUN00659.jpg
2019-02-12 17:23:39,785 DEBUG: Undistorting image YUN00631.jpg
2019-02-12 17:23:39,875 DEBUG: Undistorting image YUN00631.jpg
2019-02-12 17:23:39,879 DEBUG: Undistorting image YUN00631.jpg
2019-02-12 17:23:39,884 DEBUG: Undistorting image YUN00531.jpg
2019-02-12 17:23:40,903 DEBUG: Undistorting image YUN00531.jpg
2019-02-12 17:23:40,903 DEBUG: Undistorting image YUN00531.jpg
2019-02-12 17:23:40,904 DEBUG: Undistorting image YUN01030.jpg
2019-02-12 17:23:40,910 DEBUG: Undistorting image YUN01030.jpg
2019-02-12 17:23:40,918 DEBUG: Undistorting image YUN01030.jpg
2019-02-12 17:23:40,919 DEBUG: Undistorting image YUN00874.jpg
2019-02-12 17:23:41,331 DEBUG: Undistorting image YUN00874.jpg
2019-02-12 17:23:41,332 DEBUG: Undistorting image YUN00874.jpg
2019-02-12 17:23:41,333 DEBUG: Undistorting image YUN00914.jpg
2019-02-12 17:23:41,342 DEBUG: Undistorting image YUN00914.jpg
2019-02-12 17:23:41,342 DEBUG: Undistorting image YUN00914.jpg
2019-02-12 17:23:41,346 DEBUG: Undistorting image YUN00315.jpg
2019-02-12 17:23:41,740 DEBUG: Undistorting image YUN00315.jpg
2019-02-12 17:23:41,741 DEBUG: Undistorting image YUN00315.jpg
2019-02-12 17:23:41,742 DEBUG: Undistorting image YUN00543.jpg
2019-02-12 17:23:41,766 DEBUG: Undistorting image YUN00543.jpg
2019-02-12 17:23:41,770 DEBUG: Undistorting image YUN00543.jpg
2019-02-12 17:23:41,771 DEBUG: Undistorting image YUN00391.jpg
2019-02-12 17:23:42,152 DEBUG: Undistorting image YUN00391.jpg
2019-02-12 17:23:42,153 DEBUG: Undistorting image YUN00391.jpg
2019-02-12 17:23:42,155 DEBUG: Undistorting image YUN01086.jpg
2019-02-12 17:23:42,175 DEBUG: Undistorting image YUN01086.jpg
2019-02-12 17:23:42,175 DEBUG: Undistorting image YUN01086.jpg
2019-02-12 17:23:42,176 DEBUG: Undistorting image YUN00918.jpg
2019-02-12 17:23:42,562 DEBUG: Undistorting image YUN00918.jpg
2019-02-12 17:23:42,567 DEBUG: Undistorting image YUN00918.jpg
2019-02-12 17:23:42,567 DEBUG: Undistorting image YUN00459.jpg
2019-02-12 17:23:42,576 DEBUG: Undistorting image YUN00459.jpg
2019-02-12 17:23:42,577 DEBUG: Undistorting image YUN00459.jpg
2019-02-12 17:23:42,578 DEBUG: Undistorting image YUN00335.jpg
2019-02-12 17:23:42,906 DEBUG: Undistorting image YUN00335.jpg
2019-02-12 17:23:42,906 DEBUG: Undistorting image YUN00335.jpg
2019-02-12 17:23:42,907 DEBUG: Undistorting image YUN00547.jpg
2019-02-12 17:23:42,931 DEBUG: Undistorting image YUN00547.jpg
2019-02-12 17:23:42,936 DEBUG: Undistorting image YUN00547.jpg
2019-02-12 17:23:42,936 DEBUG: Undistorting image YUN00866.jpg
2019-02-12 17:23:43,291 DEBUG: Undistorting image YUN00866.jpg
2019-02-12 17:23:43,293 DEBUG: Undistorting image YUN00866.jpg
2019-02-12 17:23:43,294 DEBUG: Undistorting image YUN00495.jpg
2019-02-12 17:23:43,333 DEBUG: Undistorting image YUN00495.jpg
2019-02-12 17:23:43,338 DEBUG: Undistorting image YUN00495.jpg
2019-02-12 17:23:43,338 DEBUG: Undistorting image YUN01198.jpg
2019-02-12 17:23:43,697 DEBUG: Undistorting image YUN01198.jpg
2019-02-12 17:23:43,702 DEBUG: Undistorting image YUN01198.jpg
2019-02-12 17:23:43,708 DEBUG: Undistorting image YUN00635.jpg
2019-02-12 17:23:43,737 DEBUG: Undistorting image YUN00635.jpg
2019-02-12 17:23:43,737 DEBUG: Undistorting image YUN00635.jpg
2019-02-12 17:23:43,738 DEBUG: Undistorting image YUN00339.jpg
2019-02-12 17:23:44,079 DEBUG: Undistorting image YUN00339.jpg
2019-02-12 17:23:44,084 DEBUG: Undistorting image YUN00339.jpg
2019-02-12 17:23:44,085 DEBUG: Undistorting image YUN00423.jpg
2019-02-12 17:23:44,111 DEBUG: Undistorting image YUN00423.jpg
2019-02-12 17:23:44,111 DEBUG: Undistorting image YUN00423.jpg
2019-02-12 17:23:44,112 DEBUG: Undistorting image YUN01302.jpg
2019-02-12 17:23:44,554 DEBUG: Undistorting image YUN01302.jpg
2019-02-12 17:23:44,555 DEBUG: Undistorting image YUN01302.jpg
2019-02-12 17:23:44,555 DEBUG: Undistorting image YUN00327.jpg
2019-02-12 17:23:44,644 DEBUG: Undistorting image YUN00327.jpg
2019-02-12 17:23:44,645 DEBUG: Undistorting image YUN00327.jpg
2019-02-12 17:23:44,645 DEBUG: Undistorting image YUN01234.jpg
2019-02-12 17:23:44,995 DEBUG: Undistorting image YUN01234.jpg
2019-02-12 17:23:45,000 DEBUG: Undistorting image YUN01234.jpg
2019-02-12 17:23:45,001 DEBUG: Undistorting image YUN00375.jpg
2019-02-12 17:23:45,128 DEBUG: Undistorting image YUN00375.jpg
2019-02-12 17:23:45,130 DEBUG: Undistorting image YUN00375.jpg
2019-02-12 17:23:45,131 DEBUG: Undistorting image YUN01098.jpg
2019-02-12 17:23:45,409 DEBUG: Undistorting image YUN01098.jpg
2019-02-12 17:23:45,409 DEBUG: Undistorting image YUN01098.jpg
2019-02-12 17:23:45,410 DEBUG: Undistorting image YUN00363.jpg
2019-02-12 17:23:45,594 DEBUG: Undistorting image YUN00363.jpg
2019-02-12 17:23:45,594 DEBUG: Undistorting image YUN00363.jpg
2019-02-12 17:23:45,595 DEBUG: Undistorting image YUN01090.jpg
2019-02-12 17:23:45,788 DEBUG: Undistorting image YUN01090.jpg
2019-02-12 17:23:45,791 DEBUG: Undistorting image YUN01090.jpg
2019-02-12 17:23:45,792 DEBUG: Undistorting image YUN00251.jpg
2019-02-12 17:23:45,946 DEBUG: Undistorting image YUN00251.jpg
2019-02-12 17:23:45,946 DEBUG: Undistorting image YUN00251.jpg
2019-02-12 17:23:45,947 DEBUG: Undistorting image YUN00319.jpg
2019-02-12 17:23:46,162 DEBUG: Undistorting image YUN00319.jpg
2019-02-12 17:23:46,166 DEBUG: Undistorting image YUN00319.jpg
2019-02-12 17:23:46,167 DEBUG: Undistorting image YUN01270.jpg
2019-02-12 17:23:46,319 DEBUG: Undistorting image YUN01270.jpg
2019-02-12 17:23:46,320 DEBUG: Undistorting image YUN01270.jpg
2019-02-12 17:23:46,321 DEBUG: Undistorting image YUN01286.jpg
2019-02-12 17:23:46,572 DEBUG: Undistorting image YUN01286.jpg
2019-02-12 17:23:46,576 DEBUG: Undistorting image YUN01286.jpg
2019-02-12 17:23:46,577 DEBUG: Undistorting image YUN00435.jpg
2019-02-12 17:23:46,713 DEBUG: Undistorting image YUN00435.jpg
2019-02-12 17:23:46,713 DEBUG: Undistorting image YUN00435.jpg
2019-02-12 17:23:46,714 DEBUG: Undistorting image YUN00898.jpg
2019-02-12 17:23:46,977 DEBUG: Undistorting image YUN00898.jpg
2019-02-12 17:23:46,981 DEBUG: Undistorting image YUN00898.jpg
2019-02-12 17:23:46,981 DEBUG: Undistorting image YUN00922.jpg
2019-02-12 17:23:47,123 DEBUG: Undistorting image YUN00922.jpg
2019-02-12 17:23:47,124 DEBUG: Undistorting image YUN00922.jpg
2019-02-12 17:23:47,125 DEBUG: Undistorting image YUN00651.jpg
2019-02-12 17:23:47,383 DEBUG: Undistorting image YUN00651.jpg
2019-02-12 17:23:47,387 DEBUG: Undistorting image YUN00651.jpg
2019-02-12 17:23:47,388 DEBUG: Undistorting image YUN00415.jpg
2019-02-12 17:23:47,531 DEBUG: Undistorting image YUN00415.jpg
2019-02-12 17:23:47,532 DEBUG: Undistorting image YUN00415.jpg
2019-02-12 17:23:47,533 DEBUG: Undistorting image YUN00411.jpg
2019-02-12 17:23:47,791 DEBUG: Undistorting image YUN00411.jpg
2019-02-12 17:23:47,796 DEBUG: Undistorting image YUN00411.jpg
2019-02-12 17:23:47,797 DEBUG: Undistorting image YUN00966.jpg
2019-02-12 17:23:47,939 DEBUG: Undistorting image YUN00966.jpg
2019-02-12 17:23:47,940 DEBUG: Undistorting image YUN00966.jpg
2019-02-12 17:23:47,941 DEBUG: Undistorting image YUN00255.jpg
2019-02-12 17:23:48,210 DEBUG: Undistorting image YUN00255.jpg
2019-02-12 17:23:48,215 DEBUG: Undistorting image YUN00255.jpg
2019-02-12 17:23:48,216 DEBUG: Undistorting image YUN00982.jpg
2019-02-12 17:23:48,387 DEBUG: Undistorting image YUN00982.jpg
2019-02-12 17:23:48,388 DEBUG: Undistorting image YUN00982.jpg
2019-02-12 17:23:48,389 DEBUG: Undistorting image YUN00211.jpg
2019-02-12 17:23:48,635 DEBUG: Undistorting image YUN00211.jpg
2019-02-12 17:23:48,638 DEBUG: Undistorting image YUN00211.jpg
2019-02-12 17:23:48,639 DEBUG: Undistorting image YUN00627.jpg
2019-02-12 17:23:48,835 DEBUG: Undistorting image YUN00627.jpg
2019-02-12 17:23:48,836 DEBUG: Undistorting image YUN00627.jpg
2019-02-12 17:23:48,838 DEBUG: Undistorting image YUN01102.jpg
2019-02-12 17:23:49,034 DEBUG: Undistorting image YUN01102.jpg
2019-02-12 17:23:49,034 DEBUG: Undistorting image YUN01102.jpg
2019-02-12 17:23:49,035 DEBUG: Undistorting image YUN00890.jpg
2019-02-12 17:23:49,939 DEBUG: Undistorting image YUN00890.jpg
2019-02-12 17:23:49,939 DEBUG: Undistorting image YUN00890.jpg
2019-02-12 17:23:49,940 DEBUG: Undistorting image YUN01246.jpg
2019-02-12 17:23:49,977 DEBUG: Undistorting image YUN01246.jpg
2019-02-12 17:23:49,978 DEBUG: Undistorting image YUN01246.jpg
2019-02-12 17:23:49,978 DEBUG: Undistorting image YUN00643.jpg
2019-02-12 17:23:50,374 DEBUG: Undistorting image YUN00643.jpg
2019-02-12 17:23:50,374 DEBUG: Undistorting image YUN00643.jpg
2019-02-12 17:23:50,375 DEBUG: Undistorting image YUN01242.jpg
2019-02-12 17:23:50,436 DEBUG: Undistorting image YUN01242.jpg
2019-02-12 17:23:50,437 DEBUG: Undistorting image YUN01242.jpg
2019-02-12 17:23:50,441 DEBUG: Undistorting image YUN01042.jpg
2019-02-12 17:23:50,793 DEBUG: Undistorting image YUN01042.jpg
2019-02-12 17:23:50,793 DEBUG: Undistorting image YUN01042.jpg
2019-02-12 17:23:50,794 DEBUG: Undistorting image YUN00946.jpg
2019-02-12 17:23:50,863 DEBUG: Undistorting image YUN00946.jpg
2019-02-12 17:23:50,864 DEBUG: Undistorting image YUN00946.jpg
2019-02-12 17:23:50,865 DEBUG: Undistorting image YUN00503.jpg
2019-02-12 17:23:51,229 DEBUG: Undistorting image YUN00503.jpg
2019-02-12 17:23:51,235 DEBUG: Undistorting image YUN00503.jpg
2019-02-12 17:23:51,236 DEBUG: Undistorting image YUN01002.jpg
2019-02-12 17:23:51,287 DEBUG: Undistorting image YUN01002.jpg
2019-02-12 17:23:51,288 DEBUG: Undistorting image YUN01002.jpg
2019-02-12 17:23:51,289 DEBUG: Undistorting image YUN00303.jpg
2019-02-12 17:23:51,646 DEBUG: Undistorting image YUN00303.jpg
2019-02-12 17:23:51,651 DEBUG: Undistorting image YUN00303.jpg
2019-02-12 17:23:51,652 DEBUG: Undistorting image YUN00235.jpg
2019-02-12 17:23:51,727 DEBUG: Undistorting image YUN00235.jpg
2019-02-12 17:23:51,728 DEBUG: Undistorting image YUN00235.jpg
2019-02-12 17:23:51,729 DEBUG: Undistorting image YUN00926.jpg
2019-02-12 17:23:52,015 DEBUG: Undistorting image YUN00926.jpg
2019-02-12 17:23:52,019 DEBUG: Undistorting image YUN00926.jpg
2019-02-12 17:23:52,020 DEBUG: Undistorting image YUN01046.jpg
2019-02-12 17:23:52,066 DEBUG: Undistorting image YUN01046.jpg
2019-02-12 17:23:52,066 DEBUG: Undistorting image YUN01046.jpg
2019-02-12 17:23:52,067 DEBUG: Undistorting image YUN00539.jpg
2019-02-12 17:23:52,407 DEBUG: Undistorting image YUN00539.jpg
2019-02-12 17:23:52,413 DEBUG: Undistorting image YUN00539.jpg
2019-02-12 17:23:52,414 DEBUG: Undistorting image YUN00962.jpg
2019-02-12 17:23:52,457 DEBUG: Undistorting image YUN00962.jpg
2019-02-12 17:23:52,457 DEBUG: Undistorting image YUN00962.jpg
2019-02-12 17:23:52,458 DEBUG: Undistorting image YUN00930.jpg
2019-02-12 17:23:52,825 DEBUG: Undistorting image YUN00930.jpg
2019-02-12 17:23:52,829 DEBUG: Undistorting image YUN00930.jpg
2019-02-12 17:23:52,830 DEBUG: Undistorting image YUN00443.jpg
2019-02-12 17:23:52,859 DEBUG: Undistorting image YUN00443.jpg
2019-02-12 17:23:52,860 DEBUG: Undistorting image YUN00443.jpg
2019-02-12 17:23:52,860 DEBUG: Undistorting image YUN00275.jpg
2019-02-12 17:23:53,246 DEBUG: Undistorting image YUN00275.jpg
2019-02-12 17:23:53,247 DEBUG: Undistorting image YUN00275.jpg
2019-02-12 17:23:53,255 DEBUG: Undistorting image YUN00587.jpg
2019-02-12 17:23:53,382 DEBUG: Undistorting image YUN00587.jpg
2019-02-12 17:23:53,383 DEBUG: Undistorting image YUN00587.jpg
2019-02-12 17:23:53,383 DEBUG: Undistorting image YUN00511.jpg
2019-02-12 17:23:54,994 DEBUG: Undistorting image YUN00511.jpg
2019-02-12 17:23:54,994 DEBUG: Undistorting image YUN00511.jpg
2019-02-12 17:23:54,995 DEBUG: Undistorting image YUN00247.jpg
2019-02-12 17:23:55,049 DEBUG: Undistorting image YUN00247.jpg
2019-02-12 17:23:55,053 DEBUG: Undistorting image YUN00247.jpg
2019-02-12 17:23:55,054 DEBUG: Undistorting image YUN01050.jpg
2019-02-12 17:23:55,391 DEBUG: Undistorting image YUN01050.jpg
2019-02-12 17:23:55,393 DEBUG: Undistorting image YUN01050.jpg
2019-02-12 17:23:55,393 DEBUG: Undistorting image YUN00894.jpg
2019-02-12 17:23:55,488 DEBUG: Undistorting image YUN00894.jpg
2019-02-12 17:23:55,493 DEBUG: Undistorting image YUN00894.jpg
2019-02-12 17:23:55,494 DEBUG: Undistorting image YUN00451.jpg
2019-02-12 17:23:55,810 DEBUG: Undistorting image YUN00451.jpg
2019-02-12 17:23:55,811 DEBUG: Undistorting image YUN00451.jpg
2019-02-12 17:23:55,812 DEBUG: Undistorting image YUN01190.jpg
2019-02-12 17:23:55,919 DEBUG: Undistorting image YUN01190.jpg
2019-02-12 17:23:55,923 DEBUG: Undistorting image YUN01190.jpg
2019-02-12 17:23:55,925 DEBUG: Undistorting image YUN01066.jpg
2019-02-12 17:23:56,225 DEBUG: Undistorting image YUN01066.jpg
2019-02-12 17:23:56,226 DEBUG: Undistorting image YUN01066.jpg
2019-02-12 17:23:56,227 DEBUG: Undistorting image YUN00990.jpg
2019-02-12 17:23:56,345 DEBUG: Undistorting image YUN00990.jpg
2019-02-12 17:23:56,350 DEBUG: Undistorting image YUN00990.jpg
2019-02-12 17:23:56,352 DEBUG: Undistorting image YUN00607.jpg
2019-02-12 17:23:56,630 DEBUG: Undistorting image YUN00607.jpg
2019-02-12 17:23:56,631 DEBUG: Undistorting image YUN00607.jpg
2019-02-12 17:23:56,632 DEBUG: Undistorting image YUN01006.jpg
2019-02-12 17:23:56,746 DEBUG: Undistorting image YUN01006.jpg
2019-02-12 17:23:56,748 DEBUG: Undistorting image YUN01006.jpg
2019-02-12 17:23:56,748 DEBUG: Undistorting image YUN00523.jpg
2019-02-12 17:23:57,039 DEBUG: Undistorting image YUN00523.jpg
2019-02-12 17:23:57,044 DEBUG: Undistorting image YUN00523.jpg
2019-02-12 17:23:57,045 DEBUG: Undistorting image YUN01162.jpg
2019-02-12 17:23:57,141 DEBUG: Undistorting image YUN01162.jpg
2019-02-12 17:23:57,142 DEBUG: Undistorting image YUN01162.jpg
2019-02-12 17:23:57,143 DEBUG: Undistorting image YUN01010.jpg
2019-02-12 17:23:57,461 DEBUG: Undistorting image YUN01010.jpg
2019-02-12 17:23:57,468 DEBUG: Undistorting image YUN01010.jpg
2019-02-12 17:23:57,469 DEBUG: Undistorting image YUN00571.jpg
2019-02-12 17:23:57,559 DEBUG: Undistorting image YUN00571.jpg
2019-02-12 17:23:57,559 DEBUG: Undistorting image YUN00571.jpg
2019-02-12 17:23:57,560 DEBUG: Undistorting image YUN00559.jpg
2019-02-12 17:23:57,860 DEBUG: Undistorting image YUN00559.jpg
2019-02-12 17:23:57,864 DEBUG: Undistorting image YUN00559.jpg
2019-02-12 17:23:57,865 DEBUG: Undistorting image YUN01070.jpg
2019-02-12 17:23:57,913 DEBUG: Undistorting image YUN01070.jpg
2019-02-12 17:23:57,914 DEBUG: Undistorting image YUN01070.jpg
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/export_bundler /var/www/data/437e04e7-05da-4a9e-a39b-6f44910d5046/opensfm
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm export_geocoords /var/www/data/437e04e7-05da-4a9e-a39b-6f44910d5046/opensfm --transformation --proj '+units=m +no_defs=True +datum=WGS84 +proj=utm +zone=14 '
[INFO]    Running ODM OpenSfM Cell - Finished
[INFO]    Running SMVS Cell
[DEBUG]   running /code/SuperBuild/src/elibs/mve/apps/makescene/makescene /var/www/data/437e04e7-05da-4a9e-a39b-6f44910d5046/opensfm/mve /var/www/data/437e04e7-05da-4a9e-a39b-6f44910d5046/smvs
MVE Makescene (built on Jan 29 2019, 15:33:17)
Info: Detected Noah bundler format.
Reading Bundler file (229 cameras, 201201 features)...
Recognized 229 original images from Noah's Bundler.
Creating output directories...
Saving bundle file...
Writing bundle (229 cameras, 201201 features): /var/www/data/437e04e7-05da-4a9e-a39b-6f44910d5046/smvs/synth_0.out...
Processing view view_0000.mve...
Processing view view_0001.mve...
Processing view view_0002.mve...
Processing view view_0003.mve...
Processing view view_0004.mve...
Processing view view_0005.mve...
Processing view view_0006.mve...
Processing view view_0007.mve...
Processing view view_0008.mve...
Processing view view_0009.mve...
Processing view view_0010.mve...
Processing view view_0011.mve...
Processing view view_0012.mve...
Processing view view_0013.mve...
Processing view view_0014.mve...
Processing view view_0015.mve...
Processing view view_0016.mve...
Processing view view_0017.mve...
Processing view view_0018.mve...
Processing view view_0019.mve...
Processing view view_0020.mve...
Processing view view_0021.mve...
Processing view view_0022.mve...
Processing view view_0023.mve...
Processing view view_0024.mve...
Processing view view_0025.mve...
Processing view view_0026.mve...
Processing view view_0027.mve...
Processing view view_0028.mve...
Processing view view_0029.mve...
Processing view view_0030.mve...
Processing view view_0031.mve...
Processing view view_0032.mve...
Processing view view_0033.mve...
Processing view view_0034.mve...
Processing view view_0035.mve...
Processing view view_0036.mve...
Processing view view_0037.mve...
Processing view view_0038.mve...
Processing view view_0039.mve...
Processing view view_0040.mve...
Processing view view_0041.mve...
Processing view view_0042.mve...
Processing view view_0043.mve...
Processing view view_0044.mve...
Processing view view_0045.mve...
Processing view view_0046.mve...
Processing view view_0047.mve...
Processing view view_0048.mve...
Processing view view_0049.mve...
Processing view view_0050.mve...
Processing view view_0051.mve...
Processing view view_0052.mve...
Processing view view_0053.mve...
Processing view view_0054.mve...
Processing view view_0055.mve...
Processing view view_0056.mve...
Processing view view_0057.mve...
Processing view view_0058.mve...
Processing view view_0059.mve...
Processing view view_0060.mve...
Processing view view_0061.mve...
Processing view view_0062.mve...
Processing view view_0063.mve...
Processing view view_0064.mve...
Processing view view_0065.mve...
Processing view view_0066.mve...
Processing view view_0067.mve...
Processing view view_0068.mve...
Processing view view_0069.mve...
Processing view view_0070.mve...
Processing view view_0071.mve...
Processing view view_0072.mve...
Processing view view_0073.mve...
Processing view view_0074.mve...
Processing view view_0075.mve...
Processing view view_0076.mve...
Processing view view_0077.mve...
Processing view view_0078.mve...
Processing view view_0079.mve...
Processing view view_0080.mve...
Processing view view_0081.mve...
Processing view view_0082.mve...
Processing view view_0083.mve...
Processing view view_0084.mve...
Processing view view_0085.mve...
Processing view view_0086.mve...
Processing view view_0087.mve...
Processing view view_0088.mve...
Processing view view_0089.mve...
Processing view view_0090.mve...
Processing view view_0091.mve...
Processing view view_0092.mve...
Processing view view_0093.mve...
Processing view view_0094.mve...
Processing view view_0095.mve...
Processing view view_0096.mve...
Processing view view_0097.mve...
Processing view view_0098.mve...
Processing view view_0099.mve...
Processing view view_0100.mve...
Processing view view_0101.mve...
Processing view view_0102.mve...
Processing view view_0103.mve...
Processing view view_0104.mve...
Processing view view_0105.mve...
Processing view view_0106.mve...
Processing view view_0107.mve...
Processing view view_0108.mve...
Processing view view_0109.mve...
Processing view view_0110.mve...
Processing view view_0111.mve...
Processing view view_0112.mve...
Processing view view_0113.mve...
Processing view view_0114.mve...
Processing view view_0115.mve...
Processing view view_0116.mve...
Processing view view_0117.mve...
Processing view view_0118.mve...
Processing view view_0119.mve...
Processing view view_0120.mve...
Processing view view_0121.mve...
Processing view view_0122.mve...
Processing view view_0123.mve...
Processing view view_0124.mve...
Processing view view_0125.mve...
Processing view view_0126.mve...
Processing view view_0127.mve...
Processing view view_0128.mve...
Processing view view_0129.mve...
Processing view view_0130.mve...
Processing view view_0131.mve...
Processing view view_0132.mve...
Processing view view_0133.mve...
Processing view view_0134.mve...
Processing view view_0135.mve...
Processing view view_0136.mve...
Processing view view_0137.mve...
Processing view view_0138.mve...
Processing view view_0139.mve...
Processing view view_0140.mve...
Processing view view_0141.mve...
Processing view view_0142.mve...
Processing view view_0143.mve...
Processing view view_0144.mve...
Processing view view_0145.mve...
Processing view view_0146.mve...
Processing view view_0147.mve...
Processing view view_0148.mve...
Processing view view_0149.mve...
Processing view view_0150.mve...
Processing view view_0151.mve...
Processing view view_0152.mve...
Processing view view_0153.mve...
Processing view view_0154.mve...
Processing view view_0155.mve...
Processing view view_0156.mve...
Processing view view_0157.mve...
Processing view view_0158.mve...
Processing view view_0159.mve...
Processing view view_0160.mve...
Processing view view_0161.mve...
Processing view view_0162.mve...
Processing view view_0163.mve...
Processing view view_0164.mve...
Processing view view_0165.mve...
Processing view view_0166.mve...
Processing view view_0167.mve...
Processing view view_0168.mve...
Processing view view_0169.mve...
Processing view view_0170.mve...
Processing view view_0171.mve...
Processing view view_0172.mve...
Processing view view_0173.mve...
Processing view view_0174.mve...
Processing view view_0175.mve...
Processing view view_0176.mve...
Processing view view_0177.mve...
Processing view view_0178.mve...
Processing view view_0179.mve...
Processing view view_0180.mve...
Processing view view_0181.mve...
Processing view view_0182.mve...
Processing view view_0183.mve...
Processing view view_0184.mve...
Processing view view_0185.mve...
Processing view view_0186.mve...
Processing view view_0187.mve...
Processing view view_0188.mve...
Processing view view_0189.mve...
Processing view view_0190.mve...
Processing view view_0191.mve...
Processing view view_0192.mve...
Processing view view_0193.mve...
Processing view view_0194.mve...
Processing view view_0195.mve...
Processing view view_0196.mve...
Processing view view_0197.mve...
Processing view view_0198.mve...
Processing view view_0199.mve...
Processing view view_0200.mve...
Processing view view_0201.mve...
Processing view view_0202.mve...
Processing view view_0203.mve...
Processing view view_0204.mve...
Processing view view_0205.mve...
Processing view view_0206.mve...
Processing view view_0207.mve...
Processing view view_0208.mve...
Processing view view_0209.mve...
Processing view view_0210.mve...
Processing view view_0211.mve...
Processing view view_0212.mve...
Processing view view_0213.mve...
Processing view view_0214.mve...
Processing view view_0215.mve...
Processing view view_0216.mve...
Processing view view_0217.mve...
Processing view view_0218.mve...
Processing view view_0219.mve...
Processing view view_0220.mve...
Processing view view_0221.mve...
Processing view view_0222.mve...
Processing view view_0223.mve...
Processing view view_0224.mve...
Processing view view_0225.mve...
Processing view view_0226.mve...
Processing view view_0227.mve...
Processing view view_0228.mve...
Created 229 views with 229 valid cameras.
Imported 229 undistorted images.
[DEBUG]   running /code/SuperBuild/src/elibs/smvs/app/smvsrecon -t2 -a1.0 --max-pixels=1000000 -o1 --debug-lvl=0    /var/www/data/437e04e7-05da-4a9e-a39b-6f44910d5046/smvs
Shading-aware Multi-view Stereo (built on Jan 29 2019, 15:57:26)

Initializing scene with 229 views...
Initialized 229 views (max ID is 228), took 18ms.
Reading Photosynther file (229 cameras, 201201 features)...
Automatic input scale: 1
Input embedding: undist-L1
Output embedding: smvs-B1
Running view selection for 229 views...
done, took 86.305s.
Resizing input images for 229 views...
done, took 33.592s.
Starting 1/229 ID: 0 Neighbors: 124 189 184 224 167 143
Starting 2/229 ID: 1 Neighbors: 128 136 183 22 58 227
terminate called after throwing an instance of 'std::bad_alloc'
what():  std::bad_alloc
Aborted (core dumped)
Traceback (most recent call last):
File "/code/run.py", line 47, in <module>
plasm.execute(niter=1)
File "/code/scripts/smvs.py", line 85, in process
system.run('%s %s %s' % (context.smvs_path, ' '.join(config), tree.smvs))
File "/code/opendm/system.py", line 34, in run

raise Exception("Child returned {}".format(retcode))
Exception: Child returned 134

Dropbox with Images
https://www.dropbox.com/sh/ms2yfy95rtax1fn/AAB84ZiwbYe9llKuA1Pg2vuOa?dl=0

Thanks in advance for any guidence

**Comment by pierotofy** [comment]
Hey @EricGamble :hand: `terminate called after throwing an instance of 'std::bad_alloc'` indicates that you ran out of memory (I would expect that, with 8GB).

Have you tried to use `--use-opensfm-dense` instead? That might lower your memory requirements, as well as setting `--max-concurrency` to 1.

**Comment by smathermather** [comment]
FWIW, max-concurrency affect run-time but does degrade quality, while OpenSfM will reduce quality and probably runtime.

**Comment by pierotofy** [comment]
Closing, we've made lots of memory improvements since this was opened. 🙏 (update, retry?)
