### ISSUE TITLE
Importing a Task Fails if upload takes too long

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#633]
Errors out with:

```
Error handling request /api/projects/2/tasks/import
webapp    | Traceback (most recent call last):
webapp    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
webapp    |     response = get_response(request)
webapp    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
webapp    |     response = self.process_exception_by_middleware(e, request)
webapp    |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
webapp    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
webapp    |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
webapp    |     return view_func(*args, **kwargs)
webapp    |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
webapp    |     return self.dispatch(request, *args, **kwargs)
webapp    |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
webapp    |     response = self.handle_exception(exc)
webapp    |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception
webapp    |     self.raise_uncaught_exception(exc)
webapp    |   File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch
webapp    |     response = handler(request, *args, **kwargs)
webapp    |   File "/webodm/app/api/tasks.py", line 361, in post
webapp    |     for chunk in files[0].chunks():
webapp    |   File "/usr/local/lib/python3.6/site-packages/django/core/files/base.py", line 55, in chunks
webapp    |     self.seek(0)
webapp    |   File "/usr/local/lib/python3.6/tempfile.py", line 483, in func_wrapper
webapp    |     return func(*args, **kwargs)
webapp    | ValueError: seek of closed file
```

To reproduce, upload a file with a slow connection (longer than 10 minutes?).

Workaround is to use URL uploads.

**Comment by dsandson** [comment]
Piero,

Thought its worth adding in here as it may well be the same issue, however I have a server setup in Ubuntu 16.04, with Docker, and tunnelled out to the web using Ngrok. When trying to download the 'all assets' all.zip, the browser says the package is 800mb (roughly).

However trying to download it works, but appears to stop after approx ten minutes, resulting in a corrupt zip file.

My server has a relatively poor upload speed (~8mb/sec) but excellent download. I tried it logged in to the server, via localhost and the file downloaded fine so it looks like its timing out prematurely.
