### ISSUE TITLE
Error: Process exited with code 1

### ISSUE THREAD

**Issue by afrkiev** [OpenDroneMap/WebODM#640]
****************************************
PLEASE REMOVE THIS NOTE AFTER READING IT!

First of all, thank you for taking the time to report an issue.

Before you continue, make sure you are in the right place. Please open an issue only to report faults and bugs. For questions, comments and feature requests, please open a topic on http://community.opendronemap.org/c/webodm. 

Also, is your problem listed here? https://github.com/OpenDroneMap/WebODM#common-troubleshooting
If so, do not open an issue. We already know about it and steps to solve it are already documented.

Every issue needs to follow the format specified below. Do not remove the questions, simply answer each question by typing below it. If you don't know how to answer a question, write so. Questions that don't follow these guidelines will be automatically closed by our friendly IssueBot (who's not very smart and needs to see a particular format to keep an issue open).
****************************************

### How did you install WebODM? (Docker, natively, ...)?

Docker

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

Firefox 66 on Windows 10 Home 8GB RAM

### What is the problem?

Process exited with code 1

### What should be the expected behavior?

Completed map / object

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

Uploaded 8 images for test data from Samsung Galaxy S8.

I've set min-num-features to 12000 or 20000 and it didn't worked.

Resized pics to 640 - no result.

Set mesh-octree-depth: 15

Trying to get the best output to evaluate this tool as an alternative for orthos and 3d models, etc from my drone work.

VM has 5gb memory and 35 ssd space allocated

[INFO]    Running ODM Load Dataset Cell
[DEBUG]   Loading dataset from: /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/images
[DEBUG]   /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/images
[DEBUG]   Loaded 20190329_084736.jpg | camera: samsung sm-g950f | dimensions: 640 x 360 | lat: 47.8661111111 | lon: 35.1055555556 | alt: 88.0
[DEBUG]   Loaded 20190329_084726.jpg | camera: samsung sm-g950f | dimensions: 640 x 360 | lat: 47.8661111111 | lon: 35.1055555556 | alt: 88.0
[DEBUG]   Loaded 20190329_084711.jpg | camera: samsung sm-g950f | dimensions: 640 x 360 | lat: 47.8661111111 | lon: 35.1055555556 | alt: 88.0
[DEBUG]   Loaded 20190329_084719.jpg | camera: samsung sm-g950f | dimensions: 640 x 360 | lat: 47.8661111111 | lon: 35.1055555556 | alt: 88.0
[DEBUG]   Loaded 20190329_084742.jpg | camera: samsung sm-g950f | dimensions: 640 x 360 | lat: 47.8661111111 | lon: 35.1055555556 | alt: 88.0
[DEBUG]   Loaded 20190329_084751.jpg | camera: samsung sm-g950f | dimensions: 640 x 360 | lat: 47.8661111111 | lon: 35.1055555556 | alt: 88.0
[DEBUG]   Loaded 20190329_084705.jpg | camera: samsung sm-g950f | dimensions: 640 x 360 | lat: 47.8661111111 | lon: 35.1055555556 | alt: 88.0
[DEBUG]   Loaded 20190329_084731.jpg | camera: samsung sm-g950f | dimensions: 640 x 360 | lat: 47.8661111111 | lon: 35.1055555556 | alt: 88.0
[INFO]    Wrote images database: /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/images.json
[INFO]    Found 8 usable images
[DEBUG]   running /code/build/bin/odm_extract_utm -imagesPath /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/images/ -imageListFile /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/img_list.txt -outputCoordFile /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/odm_georeferencing/coords.txt  -logFile /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/odm_georeferencing/odm_georeferencing_utm_log.txt
Warning:
Directory Photo has an unexpected next pointer; ignored.
Warning:
Directory Iop has an unexpected next pointer; ignored.
Warning:
Directory GPSInfo has an unexpected next pointer; ignored.
Warning:
Directory Photo has an unexpected next pointer; ignored.
Warning:
Directory Iop has an unexpected next pointer; ignored.
Warning:
Directory GPSInfo has an unexpected next pointer; ignored.
Warning:
Directory Photo has an unexpected next pointer; ignored.
Warning:
Directory Iop has an unexpected next pointer; ignored.
Warning:
Directory GPSInfo has an unexpected next pointer; ignored.
Warning:
Directory Photo has an unexpected next pointer; ignored.
Warning:
Directory Iop has an unexpected next pointer; ignored.
Warning:
Directory GPSInfo has an unexpected next pointer; ignored.
Warning:
Directory Photo has an unexpected next pointer; ignored.
Warning:
Directory Iop has an unexpected next pointer; ignored.
Warning:
Directory GPSInfo has an unexpected next pointer; ignored.
Warning:
Directory Photo has an unexpected next pointer; ignored.
Warning:
Directory Iop has an unexpected next pointer; ignored.
Warning:
Directory GPSInfo has an unexpected next pointer; ignored.
Warning:
Directory Photo has an unexpected next pointer; ignored.
Warning:
Directory Iop has an unexpected next pointer; ignored.
Warning:
Directory GPSInfo has an unexpected next pointer; ignored.
Warning:
Directory Photo has an unexpected next pointer; ignored.
Warning:
Directory Iop has an unexpected next pointer; ignored.
Warning:
Directory GPSInfo has an unexpected next pointer; ignored.
[DEBUG]   Line: WGS84 UTM 36N
[INFO]    Running ODM Load Dataset Cell - Finished
[INFO]    Running ODM OpenSfM Cell
[DEBUG]   Altitude data detected, enabling it for GPS alignment
[DEBUG]   ['use_exif_size: no', 'feature_process_size: 640', 'feature_min_frames: 15000', 'processes: 2', 'matching_gps_neighbors: 8', 'depthmap_method: PATCH_MATCH', 'depthmap_resolution: 640', 'depthmap_min_patch_sd: 1', 'depthmap_min_consistent_views: 3', 'optimize_camera_parameters: yes', 'use_altitude_tag: True', 'align_method: naive']
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm extract_metadata /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/opensfm
/code/SuperBuild/src/opensfm/opensfm/config.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
return yaml.load(default_config_yaml)
/code/SuperBuild/src/opensfm/opensfm/config.py:150: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
new_config = yaml.load(fin)
2019-03-29 10:18:16,373 INFO: Extracting EXIF for 20190329_084736.jpg
2019-03-29 10:18:16,391 INFO: Extracting EXIF for 20190329_084726.jpg
2019-03-29 10:18:16,398 INFO: Extracting EXIF for 20190329_084711.jpg
2019-03-29 10:18:16,404 INFO: Extracting EXIF for 20190329_084719.jpg
2019-03-29 10:18:16,410 INFO: Extracting EXIF for 20190329_084742.jpg
2019-03-29 10:18:16,416 INFO: Extracting EXIF for 20190329_084751.jpg
2019-03-29 10:18:16,423 INFO: Extracting EXIF for 20190329_084705.jpg
2019-03-29 10:18:16,429 INFO: Extracting EXIF for 20190329_084731.jpg
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm detect_features /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/opensfm
/code/SuperBuild/src/opensfm/opensfm/config.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
return yaml.load(default_config_yaml)
/code/SuperBuild/src/opensfm/opensfm/config.py:150: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
new_config = yaml.load(fin)
2019-03-29 10:18:17,584 INFO: Extracting ROOT_HAHOG features for image 20190329_084736.jpg
2019-03-29 10:18:17,999 INFO: Extracting ROOT_HAHOG features for image 20190329_084726.jpg
2019-03-29 10:18:18,083 DEBUG: Found 2593 points in 0.47883105278s
2019-03-29 10:18:18,309 INFO: Extracting ROOT_HAHOG features for image 20190329_084711.jpg
2019-03-29 10:18:18,440 DEBUG: Found 2552 points in 0.432436943054s
2019-03-29 10:18:18,738 INFO: Extracting ROOT_HAHOG features for image 20190329_084719.jpg
2019-03-29 10:18:18,788 DEBUG: Found 2546 points in 0.471930027008s
2019-03-29 10:18:19,028 INFO: Extracting ROOT_HAHOG features for image 20190329_084742.jpg
2019-03-29 10:18:19,269 DEBUG: Found 2652 points in 0.524799823761s
2019-03-29 10:18:19,475 DEBUG: Found 2691 points in 0.439110040665s
2019-03-29 10:18:19,482 INFO: Extracting ROOT_HAHOG features for image 20190329_084751.jpg
2019-03-29 10:18:19,686 INFO: Extracting ROOT_HAHOG features for image 20190329_084705.jpg
2019-03-29 10:18:19,900 DEBUG: Found 2449 points in 0.407685041428s
2019-03-29 10:18:20,074 INFO: Extracting ROOT_HAHOG features for image 20190329_084731.jpg
2019-03-29 10:18:20,086 DEBUG: Found 2452 points in 0.390621900558s
2019-03-29 10:18:20,484 DEBUG: Found 2775 points in 0.402789115906s
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm match_features /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/opensfm
/code/SuperBuild/src/opensfm/opensfm/config.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
return yaml.load(default_config_yaml)
/code/SuperBuild/src/opensfm/opensfm/config.py:150: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
new_config = yaml.load(fin)
2019-03-29 10:18:21,595 INFO: Matching 28 image pairs
2019-03-29 10:18:22,201 INFO: Matching 20190329_084726.jpg  -  1 / 8
2019-03-29 10:18:22,631 DEBUG: 20190329_084726.jpg - 20190329_084742.jpg has 0 candidate matches
2019-03-29 10:18:22,683 INFO: Matching 20190329_084705.jpg  -  2 / 8
2019-03-29 10:18:23,051 DEBUG: 20190329_084726.jpg - 20190329_084736.jpg has 2 candidate matches
2019-03-29 10:18:23,073 DEBUG: 20190329_084705.jpg - 20190329_084719.jpg has 4 candidate matches
2019-03-29 10:18:23,493 DEBUG: 20190329_084726.jpg - 20190329_084731.jpg has 13 candidate matches
2019-03-29 10:18:23,504 DEBUG: 20190329_084705.jpg - 20190329_084726.jpg has 0 candidate matches
2019-03-29 10:18:23,896 DEBUG: 20190329_084726.jpg - 20190329_084751.jpg has 4 candidate matches
2019-03-29 10:18:23,939 INFO: Matching 20190329_084719.jpg  -  3 / 8
2019-03-29 10:18:23,986 DEBUG: 20190329_084705.jpg - 20190329_084736.jpg has 0 candidate matches
2019-03-29 10:18:24,370 DEBUG: 20190329_084719.jpg - 20190329_084736.jpg has 0 candidate matches
2019-03-29 10:18:24,375 DEBUG: 20190329_084705.jpg - 20190329_084711.jpg has 25 candidate matches
2019-03-29 10:18:24,381 DEBUG: Robust matching time : 0.00517797470093s
2019-03-29 10:18:24,381 DEBUG: Full matching 21 / 25, time: 0.394072055817s
2019-03-29 10:18:24,787 DEBUG: 20190329_084719.jpg - 20190329_084751.jpg has 1 candidate matches
2019-03-29 10:18:24,827 DEBUG: 20190329_084705.jpg - 20190329_084742.jpg has 1 candidate matches
2019-03-29 10:18:25,249 DEBUG: 20190329_084719.jpg - 20190329_084742.jpg has 3 candidate matches
2019-03-29 10:18:25,267 DEBUG: 20190329_084705.jpg - 20190329_084751.jpg has 1 candidate matches
2019-03-29 10:18:25,724 DEBUG: 20190329_084719.jpg - 20190329_084731.jpg has 1 candidate matches
2019-03-29 10:18:25,758 DEBUG: 20190329_084705.jpg - 20190329_084731.jpg has 1 candidate matches
2019-03-29 10:18:25,777 INFO: Matching 20190329_084736.jpg  -  4 / 8
2019-03-29 10:18:26,111 DEBUG: 20190329_084719.jpg - 20190329_084726.jpg has 6 candidate matches
2019-03-29 10:18:26,113 INFO: Matching 20190329_084742.jpg  -  5 / 8
2019-03-29 10:18:26,241 DEBUG: 20190329_084736.jpg - 20190329_084742.jpg has 57 candidate matches
2019-03-29 10:18:26,241 DEBUG: Robust matching time : 0.000231981277466s
2019-03-29 10:18:26,241 DEBUG: Full matching 52 / 57, time: 0.463876008987s
2019-03-29 10:18:26,536 DEBUG: 20190329_084742.jpg - 20190329_084751.jpg has 8 candidate matches
2019-03-29 10:18:26,538 INFO: Matching 20190329_084751.jpg  -  6 / 8
2019-03-29 10:18:26,539 INFO: Matching 20190329_084711.jpg  -  7 / 8
2019-03-29 10:18:26,665 DEBUG: 20190329_084736.jpg - 20190329_084751.jpg has 4 candidate matches
2019-03-29 10:18:26,667 INFO: Matching 20190329_084731.jpg  -  8 / 8
2019-03-29 10:18:26,921 DEBUG: 20190329_084711.jpg - 20190329_084751.jpg has 1 candidate matches
2019-03-29 10:18:27,138 DEBUG: 20190329_084731.jpg - 20190329_084742.jpg has 5 candidate matches
2019-03-29 10:18:27,314 DEBUG: 20190329_084711.jpg - 20190329_084719.jpg has 17 candidate matches
2019-03-29 10:18:27,556 DEBUG: 20190329_084731.jpg - 20190329_084751.jpg has 8 candidate matches
2019-03-29 10:18:27,719 DEBUG: 20190329_084711.jpg - 20190329_084731.jpg has 2 candidate matches
2019-03-29 10:18:28,020 DEBUG: 20190329_084731.jpg - 20190329_084736.jpg has 9 candidate matches
2019-03-29 10:18:28,088 DEBUG: 20190329_084711.jpg - 20190329_084726.jpg has 2 candidate matches
2019-03-29 10:18:28,417 DEBUG: 20190329_084711.jpg - 20190329_084736.jpg has 1 candidate matches
2019-03-29 10:18:28,743 DEBUG: 20190329_084711.jpg - 20190329_084742.jpg has 3 candidate matches
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm create_tracks /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/opensfm
/code/SuperBuild/src/opensfm/opensfm/config.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
return yaml.load(default_config_yaml)
/code/SuperBuild/src/opensfm/opensfm/config.py:150: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
new_config = yaml.load(fin)
2019-03-29 10:18:29,345 INFO: reading features
2019-03-29 10:18:29,432 DEBUG: Merging features onto tracks
2019-03-29 10:18:29,433 DEBUG: Good tracks: 73
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm reconstruct /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/opensfm
/code/SuperBuild/src/opensfm/opensfm/config.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
return yaml.load(default_config_yaml)
/code/SuperBuild/src/opensfm/opensfm/config.py:150: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
new_config = yaml.load(fin)
2019-03-29 10:18:29,990 INFO: Starting incremental reconstruction
2019-03-29 10:18:29,995 INFO: Starting reconstruction with 20190329_084736.jpg and 20190329_084742.jpg
2019-03-29 10:18:30,030 INFO: Two-view reconstruction inliers: 51 / 52
2019-03-29 10:18:30,044 INFO: Triangulated: 51
2019-03-29 10:18:30,108 DEBUG: Ceres Solver Report: Iterations: 2, Initial cost: 1.780268e+01, Final cost: 1.776585e+01, Termination: CONVERGENCE
2019-03-29 10:18:30,113 DEBUG: Ceres Solver Report: Iterations: 2, Initial cost: 1.777337e+01, Final cost: 1.775806e+01, Termination: CONVERGENCE
2019-03-29 10:18:30,132 DEBUG: Ceres Solver Report: Iterations: 32, Initial cost: 3.603698e+01, Final cost: 3.451417e+01, Termination: CONVERGENCE
2019-03-29 10:18:30,132 INFO: Removed outliers: 0
2019-03-29 10:18:30,132 INFO: -------------------------------------------------------
2019-03-29 10:18:30,134 INFO: Some images can not be added
2019-03-29 10:18:30,134 INFO: -------------------------------------------------------
2019-03-29 10:18:30,138 DEBUG: Ceres Solver Report: Iterations: 0, Initial cost: 3.451417e+01, Final cost: 3.451417e+01, Termination: CONVERGENCE
2019-03-29 10:18:30,138 INFO: Removed outliers: 0
2019-03-29 10:18:30,144 INFO: Reconstruction 0: 2 images, 51 points
2019-03-29 10:18:30,144 INFO: 1 partial reconstructions in total.
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm export_visualsfm --image_extension png --scale_focal 1 /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/opensfm
/code/SuperBuild/src/opensfm/opensfm/config.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
return yaml.load(default_config_yaml)
/code/SuperBuild/src/opensfm/opensfm/config.py:150: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
new_config = yaml.load(fin)
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm undistort --image_format png --image_scale 1 /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/opensfm
/code/SuperBuild/src/opensfm/opensfm/config.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
return yaml.load(default_config_yaml)
/code/SuperBuild/src/opensfm/opensfm/config.py:150: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
new_config = yaml.load(fin)
2019-03-29 10:18:31,340 DEBUG: Undistorting the reconstruction
2019-03-29 10:18:31,932 DEBUG: Undistorting image 20190329_084736.jpg
2019-03-29 10:18:32,318 DEBUG: Undistorting image 20190329_084736.jpg
2019-03-29 10:18:32,318 DEBUG: Undistorting image 20190329_084736.jpg
2019-03-29 10:18:32,319 DEBUG: Undistorting image 20190329_084742.jpg
2019-03-29 10:18:32,337 DEBUG: Undistorting image 20190329_084742.jpg
2019-03-29 10:18:32,337 DEBUG: Undistorting image 20190329_084742.jpg
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/export_bundler /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/opensfm
/code/SuperBuild/src/opensfm/opensfm/config.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
return yaml.load(default_config_yaml)
/code/SuperBuild/src/opensfm/opensfm/config.py:150: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
new_config = yaml.load(fin)
[DEBUG]   running PYTHONPATH=/code/SuperBuild/install/lib/python2.7/dist-packages /code/SuperBuild/src/opensfm/bin/opensfm export_geocoords /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/opensfm --transformation --proj '+proj=utm +zone=36 +datum=WGS84 +units=m +no_defs'
/code/SuperBuild/src/opensfm/opensfm/config.py:141: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
return yaml.load(default_config_yaml)
/code/SuperBuild/src/opensfm/opensfm/config.py:150: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
new_config = yaml.load(fin)
[INFO]    Running ODM OpenSfM Cell - Finished
[INFO]    Running SMVS Cell
[DEBUG]   running /code/SuperBuild/src/elibs/mve/apps/makescene/makescene /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/opensfm/mve /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/smvs
MVE Makescene (built on Mar 26 2019, 12:49:19)
Info: Detected Noah bundler format.
Reading Bundler file (8 cameras, 51 features)...
Recognized 8 original images from Noah's Bundler.
Creating output directories...
Saving bundle file...
Writing bundle (8 cameras, 51 features): /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/smvs/synth_0.out...
Processing view view_0000.mve...
Processing view view_0004.mve...
Processing view view_0001.mve...
Processing view view_0002.mve...
Processing view view_0003.mve...
Skipping view_0001.mve: Invalid camera.
Skipping view_0002.mve: Invalid camera.
Skipping view_0003.mve: Invalid camera.
Processing view view_0005.mve...
Skipping
view_0005.mve
: Invalid camera.

Processing view view_0006.mve...
Skipping
view_0006.mve
: Invalid camera.

Processing view view_0007.mve...
Skipping
view_0007.mve
: Invalid camera.

Created 8 views with 2 valid cameras.
Imported 2 undistorted images.
[DEBUG]   running /code/SuperBuild/src/elibs/smvs/app/smvsrecon -t2 -a1.0 --max-pixels=409600 -o1 --debug-lvl=0    /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/smvs
Shading-aware Multi-view Stereo (built on Mar 26 2019, 13:16:17)

Initializing scene with 2 views...
Initialized 2 views (max ID is 4), took 1ms.
Reading Photosynther file (8 cameras, 51 features)...
Automatic input scale: 0
Input embedding: undistorted
Output embedding: smvs-B0
Running view selection for 2 views...
done, took 0s.
Skipping 2 views with insufficient number of neighbors.
Skipped IDs: 0 4
All valid views are already reconstructed.
Generating Pointcloud, Cutting surfaces for 2 views ...
Done. Took: 0s
Writing PLY file (0 verts, with colors, with normals, with confidences, with values, 0 faces)...
done.
[INFO]    Filtering point cloud (statistical, meanK 16, standard deviation 2.5)
[DEBUG]   running /code/build/bin/odm_filterpoints -inputFile /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/smvs/smvs_dense_point_cloud.ply -outputFile /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/smvs/smvs_dense_point_cloud.tmp.ply -sd 2.5 -meank 16
[INFO]    Running ODM SMVS Cell - Finished
[INFO]    Running ODM Meshing Cell
[DEBUG]   Writing ODM Mesh file in: /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/odm_meshing/odm_mesh.ply
[DEBUG]   running /code/SuperBuild/src/PoissonRecon/Bin/Linux/PoissonRecon --in /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/smvs/smvs_dense_point_cloud.ply --out /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/odm_meshing/odm_mesh.dirty.ply --depth 9 --pointWeight 4 --samplesPerNode 1.0 --threads 2 --linearFit
[DEBUG]   running /code/build/bin/odm_cleanmesh -inputFile /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/odm_meshing/odm_mesh.dirty.ply -outputFile /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/odm_meshing/odm_mesh.ply -removeIslands -decimateMesh 100000
ERROR: In /build/vtk6-YpT4yb/vtk6-6.2.0+dfsg1/IO/PLY/vtkPLYWriter.cxx, line 114
vtkPLYWriter (0x24c0cf0): No data to write!
[DEBUG]   Writing ODM 2.5D Mesh file in: /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/odm_meshing/odm_25dmesh.ply
[WARNING] Cannot calculate GSD, using requested resolution of 5.0
[DEBUG]   ODM 2.5D DSM resolution: 0.2
[INFO]    Created temporary directory: /var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/odm_meshing/tmp
[INFO]    Creating DSM for 2.5D mesh
[INFO]    Creating ../var/www/data/9a326198-237f-406f-97c5-2a80301afaa7/odm_meshing/tmp/mesh_dsm_r0.282842712475 [max] from 1 files
[DEBUG]   running pdal pipeline -i /tmp/tmpjEXJV1.json > /dev/null 2>&1
Traceback (most recent call last):
File "/code/run.py", line 47, in <module>
plasm.execute(niter=1)
File "/code/scripts/odm_meshing.py", line 108, in process
method='poisson' if args.fast_orthophoto else 'gridded')
File "/code/opendm/mesh.py", line 36, in create_25dmesh
max_workers=get_max_concurrency_for_dem(available_cores, inPointCloud)
File "/code/opendm/dem/commands.py", line 34, in create_dems
fouts = list(e.map(create_dem_for_radius, radius))
File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 794, in _chain_from_iterable_of_lists
for element in iterable:
File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 589, in result_iterator
yield future.result()
File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 433, in result
return self.__get_result()
File "/usr/local/lib/python2.7/dist-packages/loky/_base.py", line 381, in __get_result
raise self._exception
Exception: Child returned 1

This was caused directly by
"""
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 418, in _process_worker
r = call_item()
File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 272, in __call__
return self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python2.7/dist-packages/loky/process_executor.py", line 337, in _process_chunk
return [fn(*args) for args in chunk]
File "/code/opendm/dem/commands.py", line 83, in create_dem
pdal.run_pipeline(json, verbose=verbose)
File "/code/opendm/dem/pdal.py", line 163, in run_pipeline
out = system.run(' '.join(cmd) + ' > /dev/null 2>&1')
File "/code/opendm/system.py", line 34, in run
raise Exception("Child returned {}".format(retcode))
Exception: Child returned 1
"""

**Comment by afrkiev** [comment]
Sorry for disturbing. I had bad dataset

**Comment by smathermather** [comment]
Thanks for closing the issue!
