### ISSUE TITLE
"dump" got wrong type of exif value

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/WebODM#664]
A dataset seem to have caused:

```
[35mworker        |[0m [2019-05-15 19:07:02,621: ERROR/ForkPoolWorker-1] worker.tasks.process_task[37942640-cb2e-4b0d-a75e-6fe5c59dc3ff]: Uncaught error! This is potentially bad. Please report it to http://github.com/OpenDroneMap/WebODM/issues: "dump" got wrong type of exif value.

[35mworker        |[0m 41728 in Exif IFD. Got as . Traceback (most recent call last):

[35mworker        |[0m   File "/usr/local/lib/python3.6/site-packages/piexif/_dump.py", line 272, in _value_to_bytes

[35mworker        |[0m     value_str = raw_value + b"\x00" * (4 - length)

[35mworker        |[0m TypeError: can only concatenate tuple (not "bytes") to tuple

[35mworker        |[0m 

[35mworker        |[0m During handling of the above exception, another exception occurred:

[35mworker        |[0m 

[35mworker        |[0m Traceback (most recent call last):

[35mworker        |[0m   File "/usr/local/lib/python3.6/site-packages/piexif/_dump.py", line 337, in _dict_to_bytes

[35mworker        |[0m     offset)

[35mworker        |[0m   File "/usr/local/lib/python3.6/site-packages/piexif/_dump.py", line 274, in _value_to_bytes

[35mworker        |[0m     raise ValueError("Got invalid type to convert.")

[35mworker        |[0m ValueError: Got invalid type to convert.

[35mworker        |[0m 

[35mworker        |[0m During handling of the above exception, another exception occurred:

[35mworker        |[0m 

[35mworker        |[0m Traceback (most recent call last):

[35mworker        |[0m   File "/webodm/worker/tasks.py", line 77, in process_task

[35mworker        |[0m     task.process()

[35mworker        |[0m   File "/webodm/app/models/task.py", line 405, in process

[35mworker        |[0m     resized_images = self.resize_images()

[35mworker        |[0m   File "/webodm/app/models/task.py", line 821, in resize_images

[35mworker        |[0m     resized_images = list(map(partial(resize_image, resize_to=self.resize_to, done=callback), images_path))

[35mworker        |[0m   File "/webodm/app/models/task.py", line 107, in resize_image

[35mworker        |[0m     im.save(resized_image_path, "JPEG", exif=piexif.dump(exif_dict), quality=100)

[35mworker        |[0m   File "/usr/local/lib/python3.6/site-packages/piexif/_dump.py", line 68, in dump

[35mworker        |[0m     exif_set = _dict_to_bytes(exif_ifd, "Exif", zeroth_length)

[35mworker        |[0m   File "/usr/local/lib/python3.6/site-packages/piexif/_dump.py", line 341, in _dict_to_bytes

[35mworker        |[0m     '{0} in {1} IFD. Got as {2}.'.format(key, ifd, type(ifd_dict[key]))

[35mworker        |[0m ValueError: "dump" got wrong type of exif value.

[35mworker        |[0m 41728 in Exif IFD. Got as .

[35mworker        |[0m 

[35mworker        |[0m [2019-05-15 19:07:06,252: ERROR/ForkPoolWorker-2] worker.tasks.process_task[b8684b45-6d57-438a-9163-4ca8bf215b57]: Uncaught error! This is potentially bad. Please report it to http://github.com/OpenDroneMap/WebODM/issues: "dump" got wrong type of exif value.

[35mworker        |[0m 41728 in Exif IFD. Got as . Traceback (most recent call last):

[35mworker        |[0m   File "/usr/local/lib/python3.6/site-packages/piexif/_dump.py", line 272, in _value_to_bytes

[35mworker        |[0m     value_str = raw_value + b"\x00" * (4 - length)

[35mworker        |[0m TypeError: can only concatenate tuple (not "bytes") to tuple

[35mworker        |[0m 

[35mworker        |[0m During handling of the above exception, another exception occurred:

[35mworker        |[0m 

[35mworker        |[0m Traceback (most recent call last):

[35mworker        |[0m   File "/usr/local/lib/python3.6/site-packages/piexif/_dump.py", line 337, in _dict_to_bytes

[35mworker        |[0m     offset)

[35mworker        |[0m   File "/usr/local/lib/python3.6/site-packages/piexif/_dump.py", line 274, in _value_to_bytes

[35mworker        |[0m     raise ValueError("Got invalid type to convert.")

[35mworker        |[0m ValueError: Got invalid type to convert.

[35mworker        |[0m 

[35mworker        |[0m During handling of the above exception, another exception occurred:

[35mworker        |[0m 

[35mworker        |[0m Traceback (most recent call last):

[35mworker        |[0m   File "/webodm/worker/tasks.py", line 77, in process_task

[35mworker        |[0m     task.process()

[35mworker        |[0m   File "/webodm/app/models/task.py", line 405, in process

[35mworker        |[0m     resized_images = self.resize_images()

[35mworker        |[0m   File "/webodm/app/models/task.py", line 821, in resize_images

[35mworker        |[0m     resized_images = list(map(partial(resize_image, resize_to=self.resize_to, done=callback), images_path))

[35mworker        |[0m   File "/webodm/app/models/task.py", line 107, in resize_image

[35mworker        |[0m     im.save(resized_image_path, "JPEG", exif=piexif.dump(exif_dict), quality=100)

[35mworker        |[0m   File "/usr/local/lib/python3.6/site-packages/piexif/_dump.py", line 68, in dump

[35mworker        |[0m     exif_set = _dict_to_bytes(exif_ifd, "Exif", zeroth_length)

[35mworker        |[0m   File "/usr/local/lib/python3.6/site-packages/piexif/_dump.py", line 341, in _dict_to_bytes

[35mworker        |[0m     '{0} in {1} IFD. Got as {2}.'.format(key, ifd, type(ifd_dict[key]))

[35mworker        |[0m ValueError: "dump" got wrong type of exif value.

[35mworker        |[0m 41728 in Exif IFD. Got as .

[35mworker        |[0m 

[35mworker        |[0m [2019-05-15 19:07:11,150: ERROR/ForkPoolWorker-2] worker.tasks.process_task[ff60d05f-298b-4f6b-a0ef-d4db4f482bdd]: Uncaught error! This is potentially bad. Please report it to http://github.com/OpenDroneMap/WebODM/issues: "dump" got wrong type of exif value.

[35mworker        |[0m 41728 in Exif IFD. Got as . Traceback (most recent call last):

[35mworker        |[0m   File "/usr/local/lib/python3.6/site-packages/piexif/_dump.py", line 272, in _value_to_bytes

[35mworker        |[0m     value_str = raw_value + b"\x00" * (4 - length)

[35mworker        |[0m TypeError: can only concatenate tuple (not "bytes") to tuple

[35mworker        |[0m 

[35mworker        |[0m During handling of the above exception, another exception occurred:

[35mworker        |[0m 

[35mworker        |[0m Traceback (most recent call last):

[35mworker        |[0m   File "/usr/local/lib/python3.6/site-packages/piexif/_dump.py", line 337, in _dict_to_bytes

[35mworker        |[0m     offset)

[35mworker        |[0m   File "/usr/local/lib/python3.6/site-packages/piexif/_dump.py", line 274, in _value_to_bytes

[35mworker        |[0m     raise ValueError("Got invalid type to convert.")

[35mworker        |[0m ValueError: Got invalid type to convert.
```

**Comment by pierotofy** [comment]
This should be now fixed in #663
