### ISSUE TITLE
Startup after fresh installation of current git fails - "FATAL:  database "webodm_dev" does not exist"

### ISSUE THREAD

**Issue by soerenGer** [OpenDroneMap/WebODM#849]
****************************************

### What's your browser and operating system?
Firefox 74.0
Linux Ubuntu 18.04

### What is the problem?

A completely fresh install of the current webodm via docker fails upon start. Setup is quite simple: Everything on a single machine with plenty of ressources (64 GB ram, 30 TB disk, 16 cores). Docker itself is not limited in any way so allowed to grab what it can.

### What should be the expected behavior?

A proper start

### How can we reproduce this? 

I started with a complete fresh install of webodm and completely removed an old installation, i.e. container, images and volumes. The magical three lines

```
git clone https://github.com/OpenDroneMap/WebODM --config core.autocrlf=input --depth 1
cd WebODM
./webodm.sh start
```

produced an error when trying to build the postgres image due to a broken DNS response. Fixing it 5 minutes later and a "webodm rebuild" everything went okay.

However, when starting, the following log indicates a problem, I think the last line gives the cause of the problem, however completely unsure what the root of the issue is.

** FATAL:  database "webodm_dev" does not exist** (see end of log)

```
Attaching to broker, webodm_node-odm_1, db, worker, webapp
broker      | 1:C 03 Apr 2020 18:23:01.965 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
broker      | 1:C 03 Apr 2020 18:23:01.965 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
broker      | 1:C 03 Apr 2020 18:23:01.965 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
broker      | 1:M 03 Apr 2020 18:23:01.967 * Running mode=standalone, port=6379.
broker      | 1:M 03 Apr 2020 18:23:01.967 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
broker      | 1:M 03 Apr 2020 18:23:01.967 # Server initialized
broker      | 1:M 03 Apr 2020 18:23:01.967 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
broker      | 1:M 03 Apr 2020 18:23:01.967 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
db          |
db          | PostgreSQL Database directory appears to contain a database; Skipping initialization
db          |
broker      | 1:M 03 Apr 2020 18:23:01.967 * Ready to accept connections
webapp      | psql: could not connect to server: Connection refused
webapp      |   Is the server running on host "db" (172.27.0.4) and accepting
webapp      |   TCP/IP connections on port 5432?
worker      | psql: could not connect to server: Connection refused
worker      |   Is the server running on host "db" (172.27.0.4) and accepting
worker      |   TCP/IP connections on port 5432?
webapp      | Postgres is unavailable - sleeping
worker      | Postgres is unavailable - sleeping
db          | LOG:  database system was shut down at 2020-04-03 17:59:09 UTC
db          | LOG:  MultiXact member wraparound protections are now enabled
db          | LOG:  database system is ready to accept connections
db          | LOG:  autovacuum launcher started
webapp      | Postgres is up - executing command
worker      | Postgres is up - executing command
worker      | wait-for-it.sh: waiting for broker:6379 without a timeout
webapp      | wait-for-it.sh: waiting for broker:6379 without a timeout
worker      | wait-for-it.sh: broker:6379 is available after 0 seconds
webapp      | wait-for-it.sh: broker:6379 is available after 0 seconds
worker      | wait-for-it.sh: waiting for webapp:8000 without a timeout
webapp      |
webapp      |  _       __     __    ____  ____  __  ___
webapp      | | |     / /__  / /_  / __ \/ __ \/  |/  /
webapp      | | | /| / / _ \/ __ \/ / / / / / / /|_/ /
webapp      | | |/ |/ /  __/ /_/ / /_/ / /_/ / /  / /
webapp      | |__/|__/\___/_.___/\____/_____/_/  /_/
webapp      |
webapp      |
webapp      | Checking python version... 3.x, good!
webapp      | Checking GDAL version... GDAL 3.0.4, released 2020/01/28, excellent!
webapp      | Running migrations
webapp      | Generated secret key
webapp      | INFO Initializing GRASS engine using /usr/bin/grass78
db          | FATAL:  database "webodm_dev" does not exist
webapp      | Traceback (most recent call last):
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
webapp      |     self.connect()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
webapp      |     self.connection = self.get_new_connection(conn_params)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
webapp      |     connection = Database.connect(**conn_params)
webapp      |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
webapp      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
webapp      | psycopg2.OperationalError: FATAL:  database "webodm_dev" does not exist
webapp      |
webapp      |
webapp      | The above exception was the direct cause of the following exception:
webapp      |
webapp      | Traceback (most recent call last):
webapp      |   File "manage.py", line 22, in <module>
webapp      |     execute_from_command_line(sys.argv)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
webapp      |     utility.execute()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
webapp      |     self.fetch_command(subcommand).run_from_argv(self.argv)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
webapp      |     self.execute(*args, **cmd_options)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
webapp      |     output = self.handle(*args, **options)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
webapp      |     res = handle_func(*args, **kwargs)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 80, in handle
webapp      |     connection.prepare_database()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 25, in prepare_database
webapp      |     with self.cursor() as cursor:
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
webapp      |     return self._cursor()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
webapp      |     self.ensure_connection()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
webapp      |     self.connect()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
webapp      |     raise dj_exc_value.with_traceback(traceback) from exc_value
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
webapp      |     self.connect()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
webapp      |     self.connection = self.get_new_connection(conn_params)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
webapp      |     connection = Database.connect(**conn_params)
webapp      |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
webapp      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
webapp      | django.db.utils.OperationalError: FATAL:  database "webodm_dev" does not exist
webapp      |
db          | FATAL:  database "webodm_dev" does not exist
webapp      | Traceback (most recent call last):
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
webapp      |     self.connect()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
webapp      |     self.connection = self.get_new_connection(conn_params)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
webapp      |     connection = Database.connect(**conn_params)
webapp      |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
webapp      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
webapp      | psycopg2.OperationalError: FATAL:  database "webodm_dev" does not exist
webapp      |
webapp      |
webapp      | The above exception was the direct cause of the following exception:
webapp      |
webapp      | Traceback (most recent call last):
webapp      |   File "manage.py", line 22, in <module>
webapp      |     execute_from_command_line(sys.argv)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
webapp      |     utility.execute()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
webapp      |     self.fetch_command(subcommand).run_from_argv(self.argv)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
webapp      |     self.execute(*args, **cmd_options)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
webapp      |     output = self.handle(*args, **options)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/shell.py", line 92, in handle
webapp      |     exec(sys.stdin.read())
webapp      |   File "<string>", line 3, in <module>
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
webapp      |     return getattr(self.get_queryset(), name)(*args, **kwargs)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 500, in update_or_create
webapp      |     with transaction.atomic(using=self.db):
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/transaction.py", line 147, in __enter__
webapp      |     if not connection.get_autocommit():
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 378, in get_autocommit
webapp      |     self.ensure_connection()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
webapp      |     self.connect()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
webapp      |     raise dj_exc_value.with_traceback(traceback) from exc_value
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
webapp      |     self.connect()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
webapp      |     self.connection = self.get_new_connection(conn_params)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
webapp      |     connection = Database.connect(**conn_params)
webapp      |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
webapp      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
webapp      | django.db.utils.OperationalError: FATAL:  database "webodm_dev" does not exist
webapp      |
webapp      | INFO Initializing GRASS engine using /usr/bin/grass78
db          | FATAL:  database "webodm_dev" does not exist
webapp      | Traceback (most recent call last):
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
webapp      |     self.connect()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
webapp      |     self.connection = self.get_new_connection(conn_params)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
webapp      |     connection = Database.connect(**conn_params)
webapp      |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
webapp      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
webapp      | psycopg2.OperationalError: FATAL:  database "webodm_dev" does not exist
webapp      |
webapp      |
webapp      | The above exception was the direct cause of the following exception:
webapp      |
webapp      | Traceback (most recent call last):
webapp      |   File "manage.py", line 22, in <module>
webapp      |     execute_from_command_line(sys.argv)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
webapp      |     utility.execute()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
webapp      |     self.fetch_command(subcommand).run_from_argv(self.argv)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
webapp      |     self.execute(*args, **cmd_options)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
webapp      |     output = self.handle(*args, **options)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/shell.py", line 92, in handle
webapp      |     exec(sys.stdin.read())
webapp      |   File "<string>", line 7, in <module>
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 268, in __iter__
webapp      |     self._fetch_all()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
webapp      |     self._result_cache = list(self._iterable_class(self))
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
webapp      |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1096, in execute_sql
webapp      |     cursor = self.connection.cursor()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
webapp      |     return self._cursor()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
webapp      |     self.ensure_connection()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
webapp      |     self.connect()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
webapp      |     raise dj_exc_value.with_traceback(traceback) from exc_value
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
webapp      |     self.connect()
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
webapp      |     self.connection = self.get_new_connection(conn_params)
webapp      |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
webapp      |     connection = Database.connect(**conn_params)
webapp      |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
webapp      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
webapp      | django.db.utils.OperationalError: FATAL:  database "webodm_dev" does not exist
```

**Comment by pierotofy** [comment]
Could we move this conversation over to the forum at https://community.opendronemap.org? :pray:

This is most likely not a bug, the `webodm_db` docker volume is probably corrupted (for some reason) and needs to be removed (it's an installation question/problem).

**Comment by soerenGer** [comment]
Okay, agreed - that helped! Just for the sake of completeness: I removed the respective volume and images und pruned everything from my docker. A clean "./webodm.sh start" started a new download of the webodm_db and finally the application came up freshly new without any problems. Thanks for the hint!
